// This file was auto-generated by Fern from our API Definition.

import * as CandidApi from "../../../../../src/api/index";
import { CandidApiClient } from "../../../../../src/Client";
import { mockServerPool } from "../../../../mock-server/MockServerPool";
import { mockOAuthScheme } from "../../../mockAuth";

describe("V1Client", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        const rawResponseBody = {
            id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            organization_id: "organization_id",
            deactivated: true,
            version: 1,
            updated_at: "2024-01-15T09:30:00Z",
            updating_user_id: "updating_user_id",
            name: "name",
            description: "description",
            fields: [
                { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
                { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
            ],
        };

        server
            .mockEndpoint()
            .get("/metadata-schemas/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.preEncounter.metadataSchemas.v1.get(
            CandidApi.preEncounter.MetadataSchemaId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
        );
        expect(response).toEqual({
            body: {
                id: CandidApi.preEncounter.MetadataSchemaId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                organizationId: CandidApi.preEncounter.OrganizationId("organization_id"),
                deactivated: true,
                version: 1,
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                updatingUserId: CandidApi.preEncounter.UserId("updating_user_id"),
                name: "name",
                description: "description",
                fields: [
                    {
                        key: "key",
                        type: "STRING",
                        enumValues: ["enum_values", "enum_values"],
                    },
                    {
                        key: "key",
                        type: "STRING",
                        enumValues: ["enum_values", "enum_values"],
                    },
                ],
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("getAll", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                {
                    id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    organization_id: "organization_id",
                    deactivated: true,
                    version: 1,
                    updated_at: "2024-01-15T09:30:00Z",
                    updating_user_id: "updating_user_id",
                    name: "name",
                    description: "description",
                    fields: [
                        { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
                        { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
                    ],
                },
                {
                    id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    organization_id: "organization_id",
                    deactivated: true,
                    version: 1,
                    updated_at: "2024-01-15T09:30:00Z",
                    updating_user_id: "updating_user_id",
                    name: "name",
                    description: "description",
                    fields: [
                        { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
                        { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
                    ],
                },
            ],
            next_page_token: "next_page_token",
            prev_page_token: "prev_page_token",
            total: 1,
        };

        server
            .mockEndpoint()
            .get("/metadata-schemas/v1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.preEncounter.metadataSchemas.v1.getAll();
        expect(response).toEqual({
            body: {
                items: [
                    {
                        id: CandidApi.preEncounter.MetadataSchemaId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        organizationId: CandidApi.preEncounter.OrganizationId("organization_id"),
                        deactivated: true,
                        version: 1,
                        updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                        updatingUserId: CandidApi.preEncounter.UserId("updating_user_id"),
                        name: "name",
                        description: "description",
                        fields: [
                            {
                                key: "key",
                                type: "STRING",
                                enumValues: ["enum_values", "enum_values"],
                            },
                            {
                                key: "key",
                                type: "STRING",
                                enumValues: ["enum_values", "enum_values"],
                            },
                        ],
                    },
                    {
                        id: CandidApi.preEncounter.MetadataSchemaId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        organizationId: CandidApi.preEncounter.OrganizationId("organization_id"),
                        deactivated: true,
                        version: 1,
                        updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                        updatingUserId: CandidApi.preEncounter.UserId("updating_user_id"),
                        name: "name",
                        description: "description",
                        fields: [
                            {
                                key: "key",
                                type: "STRING",
                                enumValues: ["enum_values", "enum_values"],
                            },
                            {
                                key: "key",
                                type: "STRING",
                                enumValues: ["enum_values", "enum_values"],
                            },
                        ],
                    },
                ],
                nextPageToken: CandidApi.preEncounter.PageToken("next_page_token"),
                prevPageToken: CandidApi.preEncounter.PageToken("prev_page_token"),
                total: 1,
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });
        const rawRequestBody = {
            name: "name",
            fields: [
                { key: "key", type: "STRING" },
                { key: "key", type: "STRING" },
            ],
        };
        const rawResponseBody = {
            id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            organization_id: "organization_id",
            deactivated: true,
            version: 1,
            updated_at: "2024-01-15T09:30:00Z",
            updating_user_id: "updating_user_id",
            name: "name",
            description: "description",
            fields: [
                { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
                { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
            ],
        };

        server
            .mockEndpoint()
            .post("/metadata-schemas/v1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.preEncounter.metadataSchemas.v1.create({
            name: "name",
            fields: [
                {
                    key: "key",
                    type: "STRING",
                },
                {
                    key: "key",
                    type: "STRING",
                },
            ],
        });
        expect(response).toEqual({
            body: {
                id: CandidApi.preEncounter.MetadataSchemaId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                organizationId: CandidApi.preEncounter.OrganizationId("organization_id"),
                deactivated: true,
                version: 1,
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                updatingUserId: CandidApi.preEncounter.UserId("updating_user_id"),
                name: "name",
                description: "description",
                fields: [
                    {
                        key: "key",
                        type: "STRING",
                        enumValues: ["enum_values", "enum_values"],
                    },
                    {
                        key: "key",
                        type: "STRING",
                        enumValues: ["enum_values", "enum_values"],
                    },
                ],
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });
        const rawRequestBody = {
            name: "name",
            fields: [
                { key: "key", type: "STRING" },
                { key: "key", type: "STRING" },
            ],
        };
        const rawResponseBody = {
            id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            organization_id: "organization_id",
            deactivated: true,
            version: 1,
            updated_at: "2024-01-15T09:30:00Z",
            updating_user_id: "updating_user_id",
            name: "name",
            description: "description",
            fields: [
                { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
                { key: "key", type: "STRING", enum_values: ["enum_values", "enum_values"] },
            ],
        };

        server
            .mockEndpoint()
            .put("/metadata-schemas/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32/version")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.preEncounter.metadataSchemas.v1.update(
            CandidApi.preEncounter.MetadataSchemaId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
            "version",
            {
                name: "name",
                fields: [
                    {
                        key: "key",
                        type: "STRING",
                    },
                    {
                        key: "key",
                        type: "STRING",
                    },
                ],
            },
        );
        expect(response).toEqual({
            body: {
                id: CandidApi.preEncounter.MetadataSchemaId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                organizationId: CandidApi.preEncounter.OrganizationId("organization_id"),
                deactivated: true,
                version: 1,
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                updatingUserId: CandidApi.preEncounter.UserId("updating_user_id"),
                name: "name",
                description: "description",
                fields: [
                    {
                        key: "key",
                        type: "STRING",
                        enumValues: ["enum_values", "enum_values"],
                    },
                    {
                        key: "key",
                        type: "STRING",
                        enumValues: ["enum_values", "enum_values"],
                    },
                ],
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("deactivate", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        server
            .mockEndpoint()
            .delete("/metadata-schemas/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32/version")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.preEncounter.metadataSchemas.v1.deactivate(
            CandidApi.preEncounter.MetadataSchemaId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
            "version",
        );
        expect(response).toEqual({
            body: undefined,
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("reactivate", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        server
            .mockEndpoint()
            .patch("/metadata-schemas/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32/version")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.preEncounter.metadataSchemas.v1.reactivate(
            CandidApi.preEncounter.MetadataSchemaId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
            "version",
        );
        expect(response).toEqual({
            body: undefined,
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });
});
