// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../index";

export interface NonInsurancePayerPaymentCreate {
    nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId;
    amountCents: number;
    paymentTimestamp?: Date;
    paymentNote?: string;
    checkNumber?: string;
    allocations: CandidApi.AllocationCreate[];
    invoiceId?: CandidApi.InvoiceId;
}
