/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../../../index";

/**
 * The unique identifier for an Appointment.
 */
export type AppointmentId = string & {
    preEncounter_appointments_v1_AppointmentId: void;
};

export function AppointmentId(value: string): CandidApi.preEncounter.appointments.v1.AppointmentId {
    return value as unknown as CandidApi.preEncounter.appointments.v1.AppointmentId;
}
