// This file was auto-generated by Fern from our API Definition.

import * as CandidApi from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import type * as serializers from "../../../../../../../index";

export const OrganizationExternalProviderId: core.serialization.Schema<
    serializers.preEncounter.organizationExternalProviders.v1.OrganizationExternalProviderId.Raw,
    CandidApi.preEncounter.organizationExternalProviders.v1.OrganizationExternalProviderId
> = core.serialization.string().transform({
    transform: CandidApi.preEncounter.organizationExternalProviders.v1.OrganizationExternalProviderId,
    untransform: (value) => value,
});

export declare namespace OrganizationExternalProviderId {
    export type Raw = string;
}
