/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { PayerUuid } from "../../../../payers/resources/v3/types/PayerUuid";
import { InsuranceType } from "./InsuranceType";

export const ExpectedNetworkStatusSubscriberInformation: core.serialization.ObjectSchema<
    serializers.expectedNetworkStatus.v2.ExpectedNetworkStatusSubscriberInformation.Raw,
    CandidApi.expectedNetworkStatus.v2.ExpectedNetworkStatusSubscriberInformation
> = core.serialization.object({
    payerUuid: core.serialization.property("payer_uuid", PayerUuid),
    memberId: core.serialization.property("member_id", core.serialization.string()),
    insuranceType: core.serialization.property("insurance_type", InsuranceType),
});

export declare namespace ExpectedNetworkStatusSubscriberInformation {
    export interface Raw {
        payer_uuid: PayerUuid.Raw;
        member_id: string;
        insurance_type: InsuranceType.Raw;
    }
}
