// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const EnterprisePermissions: core.serialization.ObjectSchema<
    serializers.enterpriseConfig.v1.EnterprisePermissions.Raw,
    CandidApi.enterpriseConfig.v1.EnterprisePermissions
> = core.serialization.object({
    writeQueues: core.serialization.property("write_queues", core.serialization.boolean()),
    writeRules: core.serialization.property("write_rules", core.serialization.boolean()),
    writeCrossCustomerRules: core.serialization.property("write_cross_customer_rules", core.serialization.boolean()),
});

export declare namespace EnterprisePermissions {
    export interface Raw {
        write_queues: boolean;
        write_rules: boolean;
        write_cross_customer_rules: boolean;
    }
}
