/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../..";

export interface PatientPaymentsPage extends CandidApi.ResourcePage {
    items: CandidApi.patientPayments.v4.PatientPayment[];
}
