// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../index";

export interface PatientPaymentInfo {
    /** The total amount of patient payments in cents for the service line. */
    totalPaymentCents: number;
    /** A list of patient payment items associated with the service line. */
    items: CandidApi.patientAr.v1.PatientPaymentAllocation[];
}
