// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import type * as serializers from "../../../../../../../index";

export const AuthorizationUnit: core.serialization.Schema<
    serializers.preEncounter.patients.v1.AuthorizationUnit.Raw,
    CandidApi.preEncounter.patients.v1.AuthorizationUnit
> = core.serialization.enum_(["VISIT", "UNIT"]);

export declare namespace AuthorizationUnit {
    export type Raw = "VISIT" | "UNIT";
}
