// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../../index";

export interface BenefitsRelatedEntity {
    entityIdentifier?: string;
    entityType?: string;
    entityName?: string;
    contactInformation?: CandidApi.preEncounter.coverages.v1.RelatedEntityContact[];
    serviceTypeCodes?: CandidApi.preEncounter.coverages.v1.ServiceTypeCode[];
}
