/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../../../index";

export interface ServiceCoverage {
    serviceCode: CandidApi.preEncounter.coverages.v1.ServiceTypeCode;
    inNetwork?: CandidApi.preEncounter.coverages.v1.ServiceCoverageDetails;
    outOfNetwork?: CandidApi.preEncounter.coverages.v1.ServiceCoverageDetails;
}
