/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as CandidApi from "../../../../api";
import * as core from "../../../../core";

export const AllocationCreate: core.serialization.ObjectSchema<
    serializers.AllocationCreate.Raw,
    CandidApi.AllocationCreate
> = core.serialization.object({
    amountCents: core.serialization.property("amount_cents", core.serialization.number()),
    recipient: core.serialization.lazy(async () => (await import("../../..")).AllocationRecipientCreate),
});

export declare namespace AllocationCreate {
    interface Raw {
        amount_cents: number;
        recipient: serializers.AllocationRecipientCreate.Raw;
    }
}
