/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as CandidApi from "../../../../api";
import * as core from "../../../../core";

export const AllocationAmountUpdate: core.serialization.ObjectSchema<
    serializers.AllocationAmountUpdate.Raw,
    CandidApi.AllocationAmountUpdate
> = core.serialization.object({
    amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
    allocations: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).AllocationCreate)
    ),
});

export declare namespace AllocationAmountUpdate {
    interface Raw {
        amount_cents?: number | null;
        allocations: serializers.AllocationCreate.Raw[];
    }
}
