/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as CandidApi from "../../../../api";
import * as core from "../../../../core";

export const RefundAllocationCreate: core.serialization.ObjectSchema<
    serializers.RefundAllocationCreate.Raw,
    CandidApi.RefundAllocationCreate
> = core.serialization.object({
    allocation: core.serialization.lazyObject(async () => (await import("../../..")).AllocationCreate),
    refundReason: core.serialization.property(
        "refund_reason",
        core.serialization.lazy(async () => (await import("../../..")).RefundReason).optional()
    ),
});

export declare namespace RefundAllocationCreate {
    interface Raw {
        allocation: serializers.AllocationCreate.Raw;
        refund_reason?: serializers.RefundReason.Raw | null;
    }
}
