// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const TaskStatus: core.serialization.Schema<serializers.tasks.TaskStatus.Raw, CandidApi.tasks.TaskStatus> =
    core.serialization.enum_([
        "finished",
        "addressed_by_provider_group",
        "sent_to_provider_group",
        "open",
        "blocked",
        "waiting_for_review",
        "in_progress",
    ]);

export declare namespace TaskStatus {
    export type Raw =
        | "finished"
        | "addressed_by_provider_group"
        | "sent_to_provider_group"
        | "open"
        | "blocked"
        | "waiting_for_review"
        | "in_progress";
}
