// This file was auto-generated by Fern from our API Definition.

export { NonInsurancePayerPaymentsClient } from "./client/Client";
export * from "./client/index";
export * from "./resources/index";
