/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../..";

export interface InsuranceAdjudicationCreate {
    payerIdentifier: CandidApi.payers.v3.PayerIdentifier;
    payee: CandidApi.remits.v1.Payee;
    postDate?: string;
    checkNumber?: string;
    checkDate: string;
    note?: string;
    claims: Record<CandidApi.ClaimId, CandidApi.insuranceAdjudications.v1.ClaimAdjudicationCreate>;
}
