/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../..";

export type ServiceLineAdjudicationId = string & {
    insuranceAdjudications_v1_ServiceLineAdjudicationId: void;
};

export function ServiceLineAdjudicationId(
    value: string
): CandidApi.insuranceAdjudications.v1.ServiceLineAdjudicationId {
    return value as unknown as CandidApi.insuranceAdjudications.v1.ServiceLineAdjudicationId;
}
