/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as CandidApi from "../../../../api";
import * as core from "../../../../core";

export const CloseTasksAndProcessClaimAction: core.serialization.ObjectSchema<
    serializers.CloseTasksAndProcessClaimAction.Raw,
    CandidApi.CloseTasksAndProcessClaimAction
> = core.serialization.object({});

export declare namespace CloseTasksAndProcessClaimAction {
    interface Raw {}
}
