// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { ClinicalTrialId } from "../../commons/types/ClinicalTrialId";

export const PatientClinicalTrialInfoCreateOptional: core.serialization.ObjectSchema<
    serializers.PatientClinicalTrialInfoCreateOptional.Raw,
    CandidApi.PatientClinicalTrialInfoCreateOptional
> = core.serialization.object({
    clinicalTrialArm: core.serialization.property("clinical_trial_arm", core.serialization.string().optional()),
    clinicalTrialId: core.serialization.property("clinical_trial_id", ClinicalTrialId.optional()),
});

export declare namespace PatientClinicalTrialInfoCreateOptional {
    export interface Raw {
        clinical_trial_arm?: string | null;
        clinical_trial_id?: ClinicalTrialId.Raw | null;
    }
}
