// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { InsuranceCardCreate } from "../../insuranceCards/resources/v2/types/InsuranceCardCreate";
import { SubscriberBase } from "./SubscriberBase";

export const SubscriberCreate: core.serialization.ObjectSchema<
    serializers.SubscriberCreate.Raw,
    CandidApi.SubscriberCreate
> = core.serialization
    .object({
        insuranceCard: core.serialization.property("insurance_card", InsuranceCardCreate),
    })
    .extend(SubscriberBase);

export declare namespace SubscriberCreate {
    export interface Raw extends SubscriberBase.Raw {
        insurance_card: InsuranceCardCreate.Raw;
    }
}
