// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../index";

/**
 * @example
 *     {
 *         data: {},
 *         chargeExternalId: "charge_external_id",
 *         preEncounterPatientId: CandidApi.PreEncounterPatientId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
 *         preEncounterAppointmentIds: [CandidApi.PreEncounterAppointmentId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"), CandidApi.PreEncounterAppointmentId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")],
 *         status: "planned"
 *     }
 */
export interface CreateChargeCaptureFromPreEncounterRequest {
    /** Charge Capture data contains all the fields needed to create an encounter, but listed as optional. Candid will use this data when attempting to bundle multiple Charge Captures into a single encounter. */
    data: CandidApi.chargeCapture.v1.ChargeCaptureData;
    /** A client-specified unique ID to associate with this encounter; for example, your internal encounter ID or a Dr. Chrono encounter ID. This field should not contain PHI. */
    chargeExternalId: string;
    preEncounterPatientId: CandidApi.PreEncounterPatientId;
    preEncounterAppointmentIds: CandidApi.PreEncounterAppointmentId[];
    /** An optional string field denoting the originating system of the charge. */
    originatingSystem?: string;
    /** An optional string field denoting the user defined category of the claim creation. */
    claimCreationCategory?: string;
    /** External URL reference that links to Charge Capture details within the external system (e.g. the EHR visit page). Send full URL format for the external link (e.g. https://emr_charge_capture_url.com/123). */
    ehrSourceUrl?: string;
    /** the status of the charge capture */
    status: CandidApi.chargeCapture.v1.ChargeCaptureStatus;
    /** Provide external attachment IDs which have been uploaded to Candid. They will be associated with the Encounter at Encounter creation time. */
    attachmentExternalDocumentIds?: string[];
}
