// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import type * as serializers from "../../../../../../index";
import { PageToken } from "../../../../../commons/types/PageToken";
import { SchemaInstance } from "../../../../../customSchemas/resources/v1/types/SchemaInstance";

export const FindByMetadataRequest: core.serialization.Schema<
    serializers.chargeCapture.v1.FindByMetadataRequest.Raw,
    CandidApi.chargeCapture.v1.FindByMetadataRequest
> = core.serialization.object({
    metadata: core.serialization.list(SchemaInstance),
    limit: core.serialization.number().optional(),
    pageToken: core.serialization.property("page_token", PageToken.optional()),
});

export declare namespace FindByMetadataRequest {
    export interface Raw {
        metadata: SchemaInstance.Raw[];
        limit?: number | null;
        page_token?: PageToken.Raw | null;
    }
}
