// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     CandidApi.organizationServiceFacilities.v2.ServiceFacilityStatus.Active
 */
export const ServiceFacilityStatus = {
    /**
     * The location is operational. */
    Active: "active",
    /**
     * The location is no longer used. */
    Inactive: "inactive",
    /**
     * TThe location is temporarily closed. */
    Suspended: "suspended",
} as const;
export type ServiceFacilityStatus = (typeof ServiceFacilityStatus)[keyof typeof ServiceFacilityStatus];
