// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient";
import { V4Client } from "../resources/v4/client/Client";

export declare namespace EncountersClient {
    export type Options = BaseClientOptions;
}

export class EncountersClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EncountersClient.Options>;
    protected _v4: V4Client | undefined;

    constructor(options: EncountersClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get v4(): V4Client {
        return (this._v4 ??= new V4Client(this._options));
    }
}
