// This file was auto-generated by Fern from our API Definition.

/**
 * Information about the encounter for the COB check.
 * Service dates must be within the past 2 years and must not be in the future.
 */
export interface CobEncounter {
    /** The date of service. Defaults to the current date if not specified. */
    dateOfService?: string;
    /** The beginning date of service. If included, end_date_of_service is also required. */
    beginningDateOfService?: string;
    /** The end date of service. If included, beginning_date_of_service is also required. */
    endDateOfService?: string;
}
