// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../../index";

/**
 * An object representing a copay estimation recommendation from AI analysis
 */
export interface CopayEstimationRecommendation {
    payload: CandidApi.preEncounter.eligibilityChecks.v1.CopayEstimationRecommendationPayload;
}
