// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import type * as serializers from "../../../../../../../index";
import { UserConfiguredPromptsResult } from "./UserConfiguredPromptsResult";

export const UserConfiguredPromptsRecommendationPayload: core.serialization.ObjectSchema<
    serializers.preEncounter.eligibilityChecks.v1.UserConfiguredPromptsRecommendationPayload.Raw,
    CandidApi.preEncounter.eligibilityChecks.v1.UserConfiguredPromptsRecommendationPayload
> = core.serialization.object({
    results: core.serialization.list(UserConfiguredPromptsResult),
});

export declare namespace UserConfiguredPromptsRecommendationPayload {
    export interface Raw {
        results: UserConfiguredPromptsResult.Raw[];
    }
}
