// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../../../../core";
import * as CandidApi from "../../../../../../../index";

export type Error =
    | CandidApi.preEncounter.lists.v1.getPatientList.Error.BadRequestError
    | CandidApi.preEncounter.lists.v1.getPatientList.Error._Unknown;

export namespace Error {
    export interface BadRequestError extends _Utils {
        errorName: "BadRequestError";
        content: CandidApi.preEncounter.ErrorBase4Xx;
    }

    export interface _Unknown extends _Utils {
        errorName: void;
        content: core.Fetcher.Error;
    }

    export interface _Utils {
        _visit: <_Result>(visitor: CandidApi.preEncounter.lists.v1.getPatientList.Error._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        badRequestError: (value: CandidApi.preEncounter.ErrorBase4Xx) => _Result;
        _other: (value: core.Fetcher.Error) => _Result;
    }
}

export const Error = {
    badRequestError: (
        value: CandidApi.preEncounter.ErrorBase4Xx,
    ): CandidApi.preEncounter.lists.v1.getPatientList.Error.BadRequestError => {
        return {
            content: value,
            errorName: "BadRequestError",
            _visit: function <_Result>(
                this: CandidApi.preEncounter.lists.v1.getPatientList.Error.BadRequestError,
                visitor: CandidApi.preEncounter.lists.v1.getPatientList.Error._Visitor<_Result>,
            ) {
                return CandidApi.preEncounter.lists.v1.getPatientList.Error._visit(this, visitor);
            },
        };
    },

    _unknown: (fetcherError: core.Fetcher.Error): CandidApi.preEncounter.lists.v1.getPatientList.Error._Unknown => {
        return {
            errorName: undefined,
            content: fetcherError,
            _visit: function <_Result>(
                this: CandidApi.preEncounter.lists.v1.getPatientList.Error._Unknown,
                visitor: CandidApi.preEncounter.lists.v1.getPatientList.Error._Visitor<_Result>,
            ) {
                return CandidApi.preEncounter.lists.v1.getPatientList.Error._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: CandidApi.preEncounter.lists.v1.getPatientList.Error,
        visitor: CandidApi.preEncounter.lists.v1.getPatientList.Error._Visitor<_Result>,
    ): _Result => {
        switch (value.errorName) {
            case "BadRequestError":
                return visitor.badRequestError(value.content);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
