/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { NoteCategory } from "./NoteCategory";
import { ClinicalNoteOptional } from "./ClinicalNoteOptional";

export const ClinicalNoteCategoryCreateOptional: core.serialization.ObjectSchema<
    serializers.encounters.v4.ClinicalNoteCategoryCreateOptional.Raw,
    CandidApi.encounters.v4.ClinicalNoteCategoryCreateOptional
> = core.serialization.object({
    category: NoteCategory.optional(),
    notes: core.serialization.list(ClinicalNoteOptional).optional(),
});

export declare namespace ClinicalNoteCategoryCreateOptional {
    export interface Raw {
        category?: NoteCategory.Raw | null;
        notes?: ClinicalNoteOptional.Raw[] | null;
    }
}
