/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { LabCodeType } from "./LabCodeType";

export const LabOptional: core.serialization.ObjectSchema<
    serializers.encounters.v4.LabOptional.Raw,
    CandidApi.encounters.v4.LabOptional
> = core.serialization.object({
    name: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    codeType: core.serialization.property("code_type", LabCodeType.optional()),
});

export declare namespace LabOptional {
    export interface Raw {
        name?: string | null;
        code?: string | null;
        code_type?: LabCodeType.Raw | null;
    }
}
