/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CandidApi } from "";

export interface SuccessfulGenerateClinicalNotesPdfResponse {
    downloadLink: CandidApi.ContentDownloadUrl;
    ttlSeconds: number;
}
