/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { PayerIdentifier } from "../../../../payers/resources/v3/types/PayerIdentifier";
import { AllocationCreate } from "../../../../financials/types/AllocationCreate";
import { RefundReason } from "../../../../financials/types/RefundReason";

export const InsuranceRefundCreate: core.serialization.ObjectSchema<
    serializers.insuranceRefunds.v1.InsuranceRefundCreate.Raw,
    CandidApi.insuranceRefunds.v1.InsuranceRefundCreate
> = core.serialization.object({
    payerIdentifier: core.serialization.property("payer_identifier", PayerIdentifier),
    amountCents: core.serialization.property("amount_cents", core.serialization.number()),
    refundTimestamp: core.serialization.property("refund_timestamp", core.serialization.date().optional()),
    refundNote: core.serialization.property("refund_note", core.serialization.string().optional()),
    allocations: core.serialization.list(AllocationCreate),
    refundReason: core.serialization.property("refund_reason", RefundReason.optional()),
});

export declare namespace InsuranceRefundCreate {
    interface Raw {
        payer_identifier: PayerIdentifier.Raw;
        amount_cents: number;
        refund_timestamp?: string | null;
        refund_note?: string | null;
        allocations: AllocationCreate.Raw[];
        refund_reason?: RefundReason.Raw | null;
    }
}
