// This file was auto-generated by Fern from our API Definition.

import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const PayerUuid: core.serialization.Schema<serializers.payers.v4.PayerUuid.Raw, CandidApi.payers.v4.PayerUuid> =
    core.serialization.string().transform({
        transform: CandidApi.payers.v4.PayerUuid,
        untransform: (value) => value,
    });

export declare namespace PayerUuid {
    export type Raw = string;
}
