/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../..";

export interface ServiceLineEraData {
    serviceLineAdjustments: CandidApi.serviceLines.v2.ServiceLineAdjustment[];
    remittanceAdviceRemarkCodes: string[];
}
