// This file was auto-generated by Fern from our API Definition.

import * as CandidApi from "../../../../src/api/index";
import { CandidApiClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";
import { mockOAuthScheme } from "../../mockAuth";

describe("V1Client", () => {
    test("get_multi", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                {
                    insurance_refund_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    payer: {
                        payer_uuid: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        payer_id: "payer_id",
                        payer_name: "payer_name",
                        availity_payer_name: "availity_payer_name",
                        availity_claims_payer_id: "availity_claims_payer_id",
                        availity_eligibility_id: "availity_eligibility_id",
                        availity_remittance_payer_id: "availity_remittance_payer_id",
                        street_address: {
                            zip_plus_four_code: "zip_plus_four_code",
                            address1: "address1",
                            address2: "address2",
                            city: "city",
                            state: "AA",
                            zip_code: "zip_code",
                        },
                    },
                    amount_cents: 1,
                    refund_timestamp: "2024-01-15T09:30:00Z",
                    refund_note: "refund_note",
                    allocations: [
                        {
                            amount_cents: 1,
                            target: {
                                type: "service_line",
                                service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            },
                            earmark: {
                                id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                target: { type: "date_of_service", value: "target" },
                                amount_earmarked_cents: 1,
                                created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            },
                            allocated_on: "2024-01-15T09:30:00Z",
                        },
                        {
                            amount_cents: 1,
                            target: {
                                type: "service_line",
                                service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            },
                            earmark: {
                                id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                target: { type: "date_of_service", value: "target" },
                                amount_earmarked_cents: 1,
                                created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            },
                            allocated_on: "2024-01-15T09:30:00Z",
                        },
                    ],
                    refund_reason: "OVERCHARGED",
                },
                {
                    insurance_refund_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    payer: {
                        payer_uuid: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        payer_id: "payer_id",
                        payer_name: "payer_name",
                        availity_payer_name: "availity_payer_name",
                        availity_claims_payer_id: "availity_claims_payer_id",
                        availity_eligibility_id: "availity_eligibility_id",
                        availity_remittance_payer_id: "availity_remittance_payer_id",
                        street_address: {
                            zip_plus_four_code: "zip_plus_four_code",
                            address1: "address1",
                            address2: "address2",
                            city: "city",
                            state: "AA",
                            zip_code: "zip_code",
                        },
                    },
                    amount_cents: 1,
                    refund_timestamp: "2024-01-15T09:30:00Z",
                    refund_note: "refund_note",
                    allocations: [
                        {
                            amount_cents: 1,
                            target: {
                                type: "service_line",
                                service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            },
                            earmark: {
                                id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                target: { type: "date_of_service", value: "target" },
                                amount_earmarked_cents: 1,
                                created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            },
                            allocated_on: "2024-01-15T09:30:00Z",
                        },
                        {
                            amount_cents: 1,
                            target: {
                                type: "service_line",
                                service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            },
                            earmark: {
                                id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                target: { type: "date_of_service", value: "target" },
                                amount_earmarked_cents: 1,
                                created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            },
                            allocated_on: "2024-01-15T09:30:00Z",
                        },
                    ],
                    refund_reason: "OVERCHARGED",
                },
            ],
            prev_page_token: "prev_page_token",
            next_page_token: "next_page_token",
        };

        server
            .mockEndpoint()
            .get("/api/insurance-refunds/v1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.insuranceRefunds.v1.getMulti();
        expect(response).toEqual({
            body: {
                items: [
                    {
                        insuranceRefundId: CandidApi.insuranceRefunds.v1.InsuranceRefundId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        payer: {
                            payerUuid: CandidApi.payers.v3.PayerUuid("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            payerId: "payer_id",
                            payerName: "payer_name",
                            availityPayerName: "availity_payer_name",
                            availityClaimsPayerId: "availity_claims_payer_id",
                            availityEligibilityId: "availity_eligibility_id",
                            availityRemittancePayerId: "availity_remittance_payer_id",
                            streetAddress: {
                                zipPlusFourCode: "zip_plus_four_code",
                                address1: "address1",
                                address2: "address2",
                                city: "city",
                                state: "AA",
                                zipCode: "zip_code",
                            },
                        },
                        amountCents: 1,
                        refundTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                        refundNote: "refund_note",
                        allocations: [
                            {
                                amountCents: 1,
                                target: {
                                    type: "service_line",
                                    serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                    claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                    encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                },
                                earmark: {
                                    id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                    target: {
                                        type: "date_of_service",
                                        value: CandidApi.Date_("target"),
                                    },
                                    amountEarmarkedCents: 1,
                                    createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                },
                                allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                            },
                            {
                                amountCents: 1,
                                target: {
                                    type: "service_line",
                                    serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                    claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                    encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                },
                                earmark: {
                                    id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                    target: {
                                        type: "date_of_service",
                                        value: CandidApi.Date_("target"),
                                    },
                                    amountEarmarkedCents: 1,
                                    createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                },
                                allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                            },
                        ],
                        refundReason: "OVERCHARGED",
                    },
                    {
                        insuranceRefundId: CandidApi.insuranceRefunds.v1.InsuranceRefundId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        payer: {
                            payerUuid: CandidApi.payers.v3.PayerUuid("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            payerId: "payer_id",
                            payerName: "payer_name",
                            availityPayerName: "availity_payer_name",
                            availityClaimsPayerId: "availity_claims_payer_id",
                            availityEligibilityId: "availity_eligibility_id",
                            availityRemittancePayerId: "availity_remittance_payer_id",
                            streetAddress: {
                                zipPlusFourCode: "zip_plus_four_code",
                                address1: "address1",
                                address2: "address2",
                                city: "city",
                                state: "AA",
                                zipCode: "zip_code",
                            },
                        },
                        amountCents: 1,
                        refundTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                        refundNote: "refund_note",
                        allocations: [
                            {
                                amountCents: 1,
                                target: {
                                    type: "service_line",
                                    serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                    claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                    encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                },
                                earmark: {
                                    id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                    target: {
                                        type: "date_of_service",
                                        value: CandidApi.Date_("target"),
                                    },
                                    amountEarmarkedCents: 1,
                                    createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                },
                                allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                            },
                            {
                                amountCents: 1,
                                target: {
                                    type: "service_line",
                                    serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                    claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                    encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                },
                                earmark: {
                                    id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                    target: {
                                        type: "date_of_service",
                                        value: CandidApi.Date_("target"),
                                    },
                                    amountEarmarkedCents: 1,
                                    createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                },
                                allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                            },
                        ],
                        refundReason: "OVERCHARGED",
                    },
                ],
                prevPageToken: CandidApi.PageToken("prev_page_token"),
                nextPageToken: CandidApi.PageToken("next_page_token"),
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        const rawResponseBody = {
            insurance_refund_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            payer: {
                payer_uuid: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                payer_id: "payer_id",
                payer_name: "payer_name",
                availity_payer_name: "availity_payer_name",
                availity_claims_payer_id: "availity_claims_payer_id",
                availity_eligibility_id: "availity_eligibility_id",
                availity_remittance_payer_id: "availity_remittance_payer_id",
                street_address: {
                    zip_plus_four_code: "zip_plus_four_code",
                    address1: "address1",
                    address2: "address2",
                    city: "city",
                    state: "AA",
                    zip_code: "zip_code",
                },
            },
            amount_cents: 1,
            refund_timestamp: "2024-01-15T09:30:00Z",
            refund_note: "refund_note",
            allocations: [
                {
                    amount_cents: 1,
                    target: {
                        type: "service_line",
                        service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    earmark: {
                        id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        target: { type: "date_of_service", value: "target" },
                        amount_earmarked_cents: 1,
                        created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    allocated_on: "2024-01-15T09:30:00Z",
                },
                {
                    amount_cents: 1,
                    target: {
                        type: "service_line",
                        service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    earmark: {
                        id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        target: { type: "date_of_service", value: "target" },
                        amount_earmarked_cents: 1,
                        created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    allocated_on: "2024-01-15T09:30:00Z",
                },
            ],
            refund_reason: "OVERCHARGED",
        };

        server
            .mockEndpoint()
            .get("/api/insurance-refunds/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.insuranceRefunds.v1.get(
            CandidApi.insuranceRefunds.v1.InsuranceRefundId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
        );
        expect(response).toEqual({
            body: {
                insuranceRefundId: CandidApi.insuranceRefunds.v1.InsuranceRefundId(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
                payer: {
                    payerUuid: CandidApi.payers.v3.PayerUuid("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                    payerId: "payer_id",
                    payerName: "payer_name",
                    availityPayerName: "availity_payer_name",
                    availityClaimsPayerId: "availity_claims_payer_id",
                    availityEligibilityId: "availity_eligibility_id",
                    availityRemittancePayerId: "availity_remittance_payer_id",
                    streetAddress: {
                        zipPlusFourCode: "zip_plus_four_code",
                        address1: "address1",
                        address2: "address2",
                        city: "city",
                        state: "AA",
                        zipCode: "zip_code",
                    },
                },
                amountCents: 1,
                refundTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                refundNote: "refund_note",
                allocations: [
                    {
                        amountCents: 1,
                        target: {
                            type: "service_line",
                            serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        },
                        earmark: {
                            id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            target: {
                                type: "date_of_service",
                                value: CandidApi.Date_("target"),
                            },
                            amountEarmarkedCents: 1,
                            createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        },
                        allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                    },
                    {
                        amountCents: 1,
                        target: {
                            type: "service_line",
                            serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        },
                        earmark: {
                            id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            target: {
                                type: "date_of_service",
                                value: CandidApi.Date_("target"),
                            },
                            amountEarmarkedCents: 1,
                            createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        },
                        allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                    },
                ],
                refundReason: "OVERCHARGED",
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });
        const rawRequestBody = {
            payer_identifier: { type: "payer_info", payer_id: "payer_id", payer_name: "payer_name" },
            amount_cents: 1,
            allocations: [
                {
                    amount_cents: 1,
                    target: { type: "service_line_by_id", value: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32" },
                },
                {
                    amount_cents: 1,
                    target: { type: "service_line_by_id", value: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32" },
                },
            ],
        };
        const rawResponseBody = {
            insurance_refund_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            payer: {
                payer_uuid: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                payer_id: "payer_id",
                payer_name: "payer_name",
                availity_payer_name: "availity_payer_name",
                availity_claims_payer_id: "availity_claims_payer_id",
                availity_eligibility_id: "availity_eligibility_id",
                availity_remittance_payer_id: "availity_remittance_payer_id",
                street_address: {
                    zip_plus_four_code: "zip_plus_four_code",
                    address1: "address1",
                    address2: "address2",
                    city: "city",
                    state: "AA",
                    zip_code: "zip_code",
                },
            },
            amount_cents: 1,
            refund_timestamp: "2024-01-15T09:30:00Z",
            refund_note: "refund_note",
            allocations: [
                {
                    amount_cents: 1,
                    target: {
                        type: "service_line",
                        service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    earmark: {
                        id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        target: { type: "date_of_service", value: "target" },
                        amount_earmarked_cents: 1,
                        created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    allocated_on: "2024-01-15T09:30:00Z",
                },
                {
                    amount_cents: 1,
                    target: {
                        type: "service_line",
                        service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    earmark: {
                        id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        target: { type: "date_of_service", value: "target" },
                        amount_earmarked_cents: 1,
                        created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    allocated_on: "2024-01-15T09:30:00Z",
                },
            ],
            refund_reason: "OVERCHARGED",
        };

        server
            .mockEndpoint()
            .post("/api/insurance-refunds/v1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.insuranceRefunds.v1.create({
            payerIdentifier: {
                type: "payer_info",
                payerId: CandidApi.payers.v3.PayerId("payer_id"),
                payerName: CandidApi.payers.v3.PayerName("payer_name"),
            },
            amountCents: 1,
            allocations: [
                {
                    amountCents: 1,
                    target: {
                        type: "service_line_by_id",
                        value: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                    },
                },
                {
                    amountCents: 1,
                    target: {
                        type: "service_line_by_id",
                        value: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                    },
                },
            ],
        });
        expect(response).toEqual({
            body: {
                insuranceRefundId: CandidApi.insuranceRefunds.v1.InsuranceRefundId(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
                payer: {
                    payerUuid: CandidApi.payers.v3.PayerUuid("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                    payerId: "payer_id",
                    payerName: "payer_name",
                    availityPayerName: "availity_payer_name",
                    availityClaimsPayerId: "availity_claims_payer_id",
                    availityEligibilityId: "availity_eligibility_id",
                    availityRemittancePayerId: "availity_remittance_payer_id",
                    streetAddress: {
                        zipPlusFourCode: "zip_plus_four_code",
                        address1: "address1",
                        address2: "address2",
                        city: "city",
                        state: "AA",
                        zipCode: "zip_code",
                    },
                },
                amountCents: 1,
                refundTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                refundNote: "refund_note",
                allocations: [
                    {
                        amountCents: 1,
                        target: {
                            type: "service_line",
                            serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        },
                        earmark: {
                            id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            target: {
                                type: "date_of_service",
                                value: CandidApi.Date_("target"),
                            },
                            amountEarmarkedCents: 1,
                            createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        },
                        allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                    },
                    {
                        amountCents: 1,
                        target: {
                            type: "service_line",
                            serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        },
                        earmark: {
                            id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            target: {
                                type: "date_of_service",
                                value: CandidApi.Date_("target"),
                            },
                            amountEarmarkedCents: 1,
                            createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        },
                        allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                    },
                ],
                refundReason: "OVERCHARGED",
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            insurance_refund_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            payer: {
                payer_uuid: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                payer_id: "payer_id",
                payer_name: "payer_name",
                availity_payer_name: "availity_payer_name",
                availity_claims_payer_id: "availity_claims_payer_id",
                availity_eligibility_id: "availity_eligibility_id",
                availity_remittance_payer_id: "availity_remittance_payer_id",
                street_address: {
                    zip_plus_four_code: "zip_plus_four_code",
                    address1: "address1",
                    address2: "address2",
                    city: "city",
                    state: "AA",
                    zip_code: "zip_code",
                },
            },
            amount_cents: 1,
            refund_timestamp: "2024-01-15T09:30:00Z",
            refund_note: "refund_note",
            allocations: [
                {
                    amount_cents: 1,
                    target: {
                        type: "service_line",
                        service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    earmark: {
                        id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        target: { type: "date_of_service", value: "target" },
                        amount_earmarked_cents: 1,
                        created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    allocated_on: "2024-01-15T09:30:00Z",
                },
                {
                    amount_cents: 1,
                    target: {
                        type: "service_line",
                        service_line_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        claim_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        encounter_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    earmark: {
                        id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        target: { type: "date_of_service", value: "target" },
                        amount_earmarked_cents: 1,
                        created_by_allocation_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    },
                    allocated_on: "2024-01-15T09:30:00Z",
                },
            ],
            refund_reason: "OVERCHARGED",
        };

        server
            .mockEndpoint()
            .patch("/api/insurance-refunds/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.insuranceRefunds.v1.update(
            CandidApi.insuranceRefunds.v1.InsuranceRefundId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
        );
        expect(response).toEqual({
            body: {
                insuranceRefundId: CandidApi.insuranceRefunds.v1.InsuranceRefundId(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
                payer: {
                    payerUuid: CandidApi.payers.v3.PayerUuid("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                    payerId: "payer_id",
                    payerName: "payer_name",
                    availityPayerName: "availity_payer_name",
                    availityClaimsPayerId: "availity_claims_payer_id",
                    availityEligibilityId: "availity_eligibility_id",
                    availityRemittancePayerId: "availity_remittance_payer_id",
                    streetAddress: {
                        zipPlusFourCode: "zip_plus_four_code",
                        address1: "address1",
                        address2: "address2",
                        city: "city",
                        state: "AA",
                        zipCode: "zip_code",
                    },
                },
                amountCents: 1,
                refundTimestamp: new Date("2024-01-15T09:30:00.000Z"),
                refundNote: "refund_note",
                allocations: [
                    {
                        amountCents: 1,
                        target: {
                            type: "service_line",
                            serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        },
                        earmark: {
                            id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            target: {
                                type: "date_of_service",
                                value: CandidApi.Date_("target"),
                            },
                            amountEarmarkedCents: 1,
                            createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        },
                        allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                    },
                    {
                        amountCents: 1,
                        target: {
                            type: "service_line",
                            serviceLineId: CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            claimId: CandidApi.ClaimId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                            encounterId: CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        },
                        earmark: {
                            id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            target: {
                                type: "date_of_service",
                                value: CandidApi.Date_("target"),
                            },
                            amountEarmarkedCents: 1,
                            createdByAllocationId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        },
                        allocatedOn: new Date("2024-01-15T09:30:00.000Z"),
                    },
                ],
                refundReason: "OVERCHARGED",
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        server
            .mockEndpoint()
            .delete("/api/insurance-refunds/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.insuranceRefunds.v1.delete(
            CandidApi.insuranceRefunds.v1.InsuranceRefundId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
        );
        expect(response).toEqual({
            body: undefined,
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });
});
