/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as CandidApi from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const ChargeCaptureBundleErrorResolution: core.serialization.Schema<
    serializers.chargeCaptureBundles.v1.ChargeCaptureBundleErrorResolution.Raw,
    CandidApi.chargeCaptureBundles.v1.ChargeCaptureBundleErrorResolution
> = core.serialization.object({
    resolvedBy: core.serialization.property("resolved_by", core.serialization.string().optional()),
    resolutionReason: core.serialization.property("resolution_reason", core.serialization.string().optional()),
});

export declare namespace ChargeCaptureBundleErrorResolution {
    export interface Raw {
        resolved_by?: string | null;
        resolution_reason?: string | null;
    }
}
