/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../../index";

/**
 * @example
 *     {
 *         name: "string",
 *         description: "string",
 *         fieldsToAdd: [{
 *                 key: "string",
 *                 type: CandidApi.Primitive.Boolean
 *             }]
 *     }
 */
export interface SchemaUpdate {
    name?: string;
    description?: string;
    /** A list of typed entries to add to schema. Only additive modifications are permitted. */
    fieldsToAdd?: CandidApi.customSchemas.v1.SchemaField[];
}
