/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const IcdCode: core.serialization.Schema<
    serializers.healthCareCodeInformation.v1.IcdCode.Raw,
    CandidApi.healthCareCodeInformation.v1.IcdCode
> = core.serialization.string().transform({
    transform: CandidApi.healthCareCodeInformation.v1.IcdCode,
    untransform: (value) => value,
});

export declare namespace IcdCode {
    export type Raw = string;
}
