/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { OccurrenceSpanCodeQualifier } from "./OccurrenceSpanCodeQualifier";
import { OccurrenceSpanCode } from "./OccurrenceSpanCode";
import { Rd8Date } from "./Rd8Date";
import { HealthCareCodeInformationNew } from "./HealthCareCodeInformationNew";

export const OccurrenceSpanInformationNew: core.serialization.ObjectSchema<
    serializers.healthCareCodeInformation.v1.OccurrenceSpanInformationNew.Raw,
    CandidApi.healthCareCodeInformation.v1.OccurrenceSpanInformationNew
> = core.serialization
    .object({
        occurrenceSpanCodeQualifier: core.serialization.property(
            "occurrence_span_code_qualifier",
            OccurrenceSpanCodeQualifier,
        ),
        occurrenceSpanCode: core.serialization.property("occurrence_span_code", OccurrenceSpanCode),
        occurrenceSpanDate: core.serialization.property("occurrence_span_date", Rd8Date),
    })
    .extend(HealthCareCodeInformationNew);

export declare namespace OccurrenceSpanInformationNew {
    export interface Raw extends HealthCareCodeInformationNew.Raw {
        occurrence_span_code_qualifier: OccurrenceSpanCodeQualifier.Raw;
        occurrence_span_code: OccurrenceSpanCode.Raw;
        occurrence_span_date: Rd8Date.Raw;
    }
}
