// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const OtherDiagnosisInformationCodeQualifier: core.serialization.Schema<
    serializers.healthCareCodeInformation.v1.OtherDiagnosisInformationCodeQualifier.Raw,
    CandidApi.healthCareCodeInformation.v1.OtherDiagnosisInformationCodeQualifier
> = core.serialization.enum_(["BF", "ABF"]);

export declare namespace OtherDiagnosisInformationCodeQualifier {
    export type Raw = "BF" | "ABF";
}
