// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const PresentOnAdmissionIndicatorCode: core.serialization.Schema<
    serializers.healthCareCodeInformation.v1.PresentOnAdmissionIndicatorCode.Raw,
    CandidApi.healthCareCodeInformation.v1.PresentOnAdmissionIndicatorCode
> = core.serialization.enum_(["Y", "N", "U", "W", "1"]);

export declare namespace PresentOnAdmissionIndicatorCode {
    export type Raw = "Y" | "N" | "U" | "W" | "1";
}
