// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";
import { HealthCareCodeInformationNew } from "./HealthCareCodeInformationNew";
import { TreatmentCode } from "./TreatmentCode";
import { TreatmentCodeQualifier } from "./TreatmentCodeQualifier";

export const TreatmentCodeInformationNew: core.serialization.ObjectSchema<
    serializers.healthCareCodeInformation.v1.TreatmentCodeInformationNew.Raw,
    CandidApi.healthCareCodeInformation.v1.TreatmentCodeInformationNew
> = core.serialization
    .object({
        treatmentCodeQualifier: core.serialization.property("treatment_code_qualifier", TreatmentCodeQualifier),
        treatmentCode: core.serialization.property("treatment_code", TreatmentCode),
    })
    .extend(HealthCareCodeInformationNew);

export declare namespace TreatmentCodeInformationNew {
    export interface Raw extends HealthCareCodeInformationNew.Raw {
        treatment_code_qualifier: TreatmentCodeQualifier.Raw;
        treatment_code: TreatmentCode.Raw;
    }
}
