// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";
import { ResourcePage } from "../../../../commons/types/ResourcePage";
import { PatientPayment } from "./PatientPayment";

export const PatientPaymentsPage: core.serialization.ObjectSchema<
    serializers.patientPayments.v4.PatientPaymentsPage.Raw,
    CandidApi.patientPayments.v4.PatientPaymentsPage
> = core.serialization
    .object({
        items: core.serialization.list(PatientPayment),
    })
    .extend(ResourcePage);

export declare namespace PatientPaymentsPage {
    export interface Raw extends ResourcePage.Raw {
        items: PatientPayment.Raw[];
    }
}
