/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const PayerPlanGroupSortField: core.serialization.Schema<
    serializers.payerPlanGroups.v1.PayerPlanGroupSortField.Raw,
    CandidApi.payerPlanGroups.v1.PayerPlanGroupSortField
> = core.serialization.enum_(["plan_group_name", "plan_type", "created_at"]);

export declare namespace PayerPlanGroupSortField {
    export type Raw = "plan_group_name" | "plan_type" | "created_at";
}
