/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { CandidApi } from "";
import * as core from "../../../../../../core";

export const RxCui: core.serialization.Schema<serializers.encounters.v3.RxCui.Raw, CandidApi.encounters.v3.RxCui> =
    core.serialization.string();

export declare namespace RxCui {
    type Raw = string;
}
