/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ProviderCredentialingSpanId } from "./ProviderCredentialingSpanId";
import { OrganizationProviderV2 } from "../../../../organizationProviders/resources/v3/types/OrganizationProviderV2";
import { Regions } from "../../../../commons/types/Regions";
import { BaseCredentialingSpan } from "./BaseCredentialingSpan";

export const ProviderCredentialingSpan: core.serialization.ObjectSchema<
    serializers.credentialing.v2.ProviderCredentialingSpan.Raw,
    CandidApi.credentialing.v2.ProviderCredentialingSpan
> = core.serialization
    .object({
        providerCredentialingSpanId: core.serialization.property(
            "provider_credentialing_span_id",
            ProviderCredentialingSpanId,
        ),
        renderingProvider: core.serialization.property("rendering_provider", OrganizationProviderV2),
        regions: Regions,
        medallionPayerEnrollmentId: core.serialization.property(
            "medallion_payer_enrollment_id",
            core.serialization.string().optional(),
        ),
        source: core.serialization.string(),
    })
    .extend(BaseCredentialingSpan);

export declare namespace ProviderCredentialingSpan {
    export interface Raw extends BaseCredentialingSpan.Raw {
        provider_credentialing_span_id: ProviderCredentialingSpanId.Raw;
        rendering_provider: OrganizationProviderV2.Raw;
        regions: Regions.Raw;
        medallion_payer_enrollment_id?: string | null;
        source: string;
    }
}
