/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as CandidApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const TaskActionType: core.serialization.Schema<
    serializers.tasks.v3.TaskActionType.Raw,
    CandidApi.tasks.v3.TaskActionType
> = core.serialization.enum_(["close_task", "close_task_and_reprocess"]);

export declare namespace TaskActionType {
    type Raw = "close_task" | "close_task_and_reprocess";
}
