// This file was auto-generated by Fern from our API Definition.

import * as CandidApi from "../../../../src/api/index";
import { CandidApiClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";
import { mockOAuthScheme } from "../../mockAuth";

describe("V1Client", () => {
    test("create", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            name: "name",
            description: "description",
            category: "category",
            enabled: true,
            address: {
                zip_plus_four_code: "zip_plus_four_code",
                address1: "address1",
                address2: "address2",
                city: "city",
                state: "AA",
                zip_code: "zip_code",
            },
            clinical_trials: [
                {
                    clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    is_active: true,
                    name: "name",
                    clinical_trial_number: "clinical_trial_number",
                    clinical_trial_phase: "Phase 1",
                },
                {
                    clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    is_active: true,
                    name: "name",
                    clinical_trial_number: "clinical_trial_number",
                    clinical_trial_phase: "Phase 1",
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/api/non-insurance-payers/v1")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.nonInsurancePayers.v1.create({
            name: "name",
        });
        expect(response).toEqual({
            body: {
                nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
                name: "name",
                description: "description",
                category: "category",
                enabled: true,
                address: {
                    zipPlusFourCode: "zip_plus_four_code",
                    address1: "address1",
                    address2: "address2",
                    city: "city",
                    state: "AA",
                    zipCode: "zip_code",
                },
                clinicalTrials: [
                    {
                        clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        isActive: true,
                        name: "name",
                        clinicalTrialNumber: "clinical_trial_number",
                        clinicalTrialPhase: "Phase 1",
                    },
                    {
                        clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        isActive: true,
                        name: "name",
                        clinicalTrialNumber: "clinical_trial_number",
                        clinicalTrialPhase: "Phase 1",
                    },
                ],
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("toggle_enablement", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });
        const rawRequestBody = { enabled: true };
        const rawResponseBody = {
            non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            name: "name",
            description: "description",
            category: "category",
            enabled: true,
            address: {
                zip_plus_four_code: "zip_plus_four_code",
                address1: "address1",
                address2: "address2",
                city: "city",
                state: "AA",
                zip_code: "zip_code",
            },
            clinical_trials: [
                {
                    clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    is_active: true,
                    name: "name",
                    clinical_trial_number: "clinical_trial_number",
                    clinical_trial_phase: "Phase 1",
                },
                {
                    clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    is_active: true,
                    name: "name",
                    clinical_trial_number: "clinical_trial_number",
                    clinical_trial_phase: "Phase 1",
                },
            ],
        };
        server
            .mockEndpoint()
            .patch("/api/non-insurance-payers/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32/toggle_enablement")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.nonInsurancePayers.v1.toggleEnablement(
            CandidApi.nonInsurancePayers.v1.NonInsurancePayerId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
            {
                enabled: true,
            },
        );
        expect(response).toEqual({
            body: {
                nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
                name: "name",
                description: "description",
                category: "category",
                enabled: true,
                address: {
                    zipPlusFourCode: "zip_plus_four_code",
                    address1: "address1",
                    address2: "address2",
                    city: "city",
                    state: "AA",
                    zipCode: "zip_code",
                },
                clinicalTrials: [
                    {
                        clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        isActive: true,
                        name: "name",
                        clinicalTrialNumber: "clinical_trial_number",
                        clinicalTrialPhase: "Phase 1",
                    },
                    {
                        clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        isActive: true,
                        name: "name",
                        clinicalTrialNumber: "clinical_trial_number",
                        clinicalTrialPhase: "Phase 1",
                    },
                ],
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("get_multi", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                {
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    name: "name",
                    description: "description",
                    category: "category",
                    enabled: true,
                    address: {
                        zip_plus_four_code: "zip_plus_four_code",
                        address1: "address1",
                        address2: "address2",
                        city: "city",
                        state: "AA",
                        zip_code: "zip_code",
                    },
                    clinical_trials: [
                        {
                            clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            is_active: true,
                            name: "name",
                            clinical_trial_number: "clinical_trial_number",
                            clinical_trial_phase: "Phase 1",
                        },
                        {
                            clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            is_active: true,
                            name: "name",
                            clinical_trial_number: "clinical_trial_number",
                            clinical_trial_phase: "Phase 1",
                        },
                    ],
                },
                {
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    name: "name",
                    description: "description",
                    category: "category",
                    enabled: true,
                    address: {
                        zip_plus_four_code: "zip_plus_four_code",
                        address1: "address1",
                        address2: "address2",
                        city: "city",
                        state: "AA",
                        zip_code: "zip_code",
                    },
                    clinical_trials: [
                        {
                            clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            is_active: true,
                            name: "name",
                            clinical_trial_number: "clinical_trial_number",
                            clinical_trial_phase: "Phase 1",
                        },
                        {
                            clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                            is_active: true,
                            name: "name",
                            clinical_trial_number: "clinical_trial_number",
                            clinical_trial_phase: "Phase 1",
                        },
                    ],
                },
            ],
            prev_page_token: "prev_page_token",
            next_page_token: "next_page_token",
        };
        server
            .mockEndpoint()
            .get("/api/non-insurance-payers/v1")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.nonInsurancePayers.v1.getMulti();
        expect(response).toEqual({
            body: {
                items: [
                    {
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        name: "name",
                        description: "description",
                        category: "category",
                        enabled: true,
                        address: {
                            zipPlusFourCode: "zip_plus_four_code",
                            address1: "address1",
                            address2: "address2",
                            city: "city",
                            state: "AA",
                            zipCode: "zip_code",
                        },
                        clinicalTrials: [
                            {
                                clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                ),
                                isActive: true,
                                name: "name",
                                clinicalTrialNumber: "clinical_trial_number",
                                clinicalTrialPhase: "Phase 1",
                            },
                            {
                                clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                ),
                                isActive: true,
                                name: "name",
                                clinicalTrialNumber: "clinical_trial_number",
                                clinicalTrialPhase: "Phase 1",
                            },
                        ],
                    },
                    {
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        name: "name",
                        description: "description",
                        category: "category",
                        enabled: true,
                        address: {
                            zipPlusFourCode: "zip_plus_four_code",
                            address1: "address1",
                            address2: "address2",
                            city: "city",
                            state: "AA",
                            zipCode: "zip_code",
                        },
                        clinicalTrials: [
                            {
                                clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                ),
                                isActive: true,
                                name: "name",
                                clinicalTrialNumber: "clinical_trial_number",
                                clinicalTrialPhase: "Phase 1",
                            },
                            {
                                clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                                nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                                ),
                                isActive: true,
                                name: "name",
                                clinicalTrialNumber: "clinical_trial_number",
                                clinicalTrialPhase: "Phase 1",
                            },
                        ],
                    },
                ],
                prevPageToken: CandidApi.PageToken("prev_page_token"),
                nextPageToken: CandidApi.PageToken("next_page_token"),
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("getCategories", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        const rawResponseBody = {
            items: ["items", "items"],
            prev_page_token: "prev_page_token",
            next_page_token: "next_page_token",
        };
        server
            .mockEndpoint()
            .get("/api/non-insurance-payers/v1/categories")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.nonInsurancePayers.v1.getCategories();
        expect(response).toEqual({
            body: {
                items: ["items", "items"],
                prevPageToken: CandidApi.PageToken("prev_page_token"),
                nextPageToken: CandidApi.PageToken("next_page_token"),
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        const rawResponseBody = {
            non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            name: "name",
            description: "description",
            category: "category",
            enabled: true,
            address: {
                zip_plus_four_code: "zip_plus_four_code",
                address1: "address1",
                address2: "address2",
                city: "city",
                state: "AA",
                zip_code: "zip_code",
            },
            clinical_trials: [
                {
                    clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    is_active: true,
                    name: "name",
                    clinical_trial_number: "clinical_trial_number",
                    clinical_trial_phase: "Phase 1",
                },
                {
                    clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    is_active: true,
                    name: "name",
                    clinical_trial_number: "clinical_trial_number",
                    clinical_trial_phase: "Phase 1",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/api/non-insurance-payers/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.nonInsurancePayers.v1.get(
            CandidApi.nonInsurancePayers.v1.NonInsurancePayerId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
        );
        expect(response).toEqual({
            body: {
                nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
                name: "name",
                description: "description",
                category: "category",
                enabled: true,
                address: {
                    zipPlusFourCode: "zip_plus_four_code",
                    address1: "address1",
                    address2: "address2",
                    city: "city",
                    state: "AA",
                    zipCode: "zip_code",
                },
                clinicalTrials: [
                    {
                        clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        isActive: true,
                        name: "name",
                        clinicalTrialNumber: "clinical_trial_number",
                        clinicalTrialPhase: "Phase 1",
                    },
                    {
                        clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        isActive: true,
                        name: "name",
                        clinicalTrialNumber: "clinical_trial_number",
                        clinicalTrialPhase: "Phase 1",
                    },
                ],
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
            name: "name",
            description: "description",
            category: "category",
            enabled: true,
            address: {
                zip_plus_four_code: "zip_plus_four_code",
                address1: "address1",
                address2: "address2",
                city: "city",
                state: "AA",
                zip_code: "zip_code",
            },
            clinical_trials: [
                {
                    clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    is_active: true,
                    name: "name",
                    clinical_trial_number: "clinical_trial_number",
                    clinical_trial_phase: "Phase 1",
                },
                {
                    clinical_trial_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    non_insurance_payer_id: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                    is_active: true,
                    name: "name",
                    clinical_trial_number: "clinical_trial_number",
                    clinical_trial_phase: "Phase 1",
                },
            ],
        };
        server
            .mockEndpoint()
            .patch("/api/non-insurance-payers/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.nonInsurancePayers.v1.update(
            CandidApi.nonInsurancePayers.v1.NonInsurancePayerId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
            {},
        );
        expect(response).toEqual({
            body: {
                nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                    "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                ),
                name: "name",
                description: "description",
                category: "category",
                enabled: true,
                address: {
                    zipPlusFourCode: "zip_plus_four_code",
                    address1: "address1",
                    address2: "address2",
                    city: "city",
                    state: "AA",
                    zipCode: "zip_code",
                },
                clinicalTrials: [
                    {
                        clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        isActive: true,
                        name: "name",
                        clinicalTrialNumber: "clinical_trial_number",
                        clinicalTrialPhase: "Phase 1",
                    },
                    {
                        clinicalTrialId: CandidApi.ClinicalTrialId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
                        nonInsurancePayerId: CandidApi.nonInsurancePayers.v1.NonInsurancePayerId(
                            "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
                        ),
                        isActive: true,
                        name: "name",
                        clinicalTrialNumber: "clinical_trial_number",
                        clinicalTrialPhase: "Phase 1",
                    },
                ],
            },
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        mockOAuthScheme(server);

        const client = new CandidApiClient({
            maxRetries: 0,
            clientId: "YOUR_CLIENT_ID",
            clientSecret: "YOUR_CLIENT_SECRET",
            environment: { candidApi: server.baseUrl, preEncounter: server.baseUrl },
        });

        server
            .mockEndpoint()
            .delete("/api/non-insurance-payers/v1/d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.nonInsurancePayers.v1.delete(
            CandidApi.nonInsurancePayers.v1.NonInsurancePayerId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"),
        );
        expect(response).toEqual({
            body: undefined,
            ok: true,
            headers: expect.any(Object),
            rawResponse: expect.any(Object),
        });
    });
});
