// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const RelatedCausesCode: core.serialization.Schema<
    serializers.relatedCauses.v1.RelatedCausesCode.Raw,
    CandidApi.relatedCauses.v1.RelatedCausesCode
> = core.serialization.enum_(["AA", "AB", "AP", "EM", "OA", "ZZ"]);

export declare namespace RelatedCausesCode {
    export type Raw = "AA" | "AB" | "AP" | "EM" | "OA" | "ZZ";
}
