/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../index";
import * as core from "../../../../../../core";

export type Error =
    | CandidApi.eligibility.v2.submitEligibilityCheck.Error.HttpServiceUnavailableError
    | CandidApi.eligibility.v2.submitEligibilityCheck.Error._Unknown;

export namespace Error {
    export interface HttpServiceUnavailableError extends _Utils {
        errorName: "HttpServiceUnavailableError";
        content: CandidApi.HttpServiceUnavailableErrorMessage;
    }

    export interface _Unknown extends _Utils {
        errorName: void;
        content: core.Fetcher.Error;
    }

    export interface _Utils {
        _visit: <_Result>(visitor: CandidApi.eligibility.v2.submitEligibilityCheck.Error._Visitor<_Result>) => _Result;
    }

    export interface _Visitor<_Result> {
        httpServiceUnavailableError: (value: CandidApi.HttpServiceUnavailableErrorMessage) => _Result;
        _other: (value: core.Fetcher.Error) => _Result;
    }
}

export const Error = {
    httpServiceUnavailableError: (
        value: CandidApi.HttpServiceUnavailableErrorMessage,
    ): CandidApi.eligibility.v2.submitEligibilityCheck.Error.HttpServiceUnavailableError => {
        return {
            content: value,
            errorName: "HttpServiceUnavailableError",
            _visit: function <_Result>(
                this: CandidApi.eligibility.v2.submitEligibilityCheck.Error.HttpServiceUnavailableError,
                visitor: CandidApi.eligibility.v2.submitEligibilityCheck.Error._Visitor<_Result>,
            ) {
                return CandidApi.eligibility.v2.submitEligibilityCheck.Error._visit(this, visitor);
            },
        };
    },

    _unknown: (fetcherError: core.Fetcher.Error): CandidApi.eligibility.v2.submitEligibilityCheck.Error._Unknown => {
        return {
            errorName: undefined,
            content: fetcherError,
            _visit: function <_Result>(
                this: CandidApi.eligibility.v2.submitEligibilityCheck.Error._Unknown,
                visitor: CandidApi.eligibility.v2.submitEligibilityCheck.Error._Visitor<_Result>,
            ) {
                return CandidApi.eligibility.v2.submitEligibilityCheck.Error._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(
        value: CandidApi.eligibility.v2.submitEligibilityCheck.Error,
        visitor: CandidApi.eligibility.v2.submitEligibilityCheck.Error._Visitor<_Result>,
    ): _Result => {
        switch (value.errorName) {
            case "HttpServiceUnavailableError":
                return visitor.httpServiceUnavailableError(value.content);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
