// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../index";

export interface ContractCreate extends CandidApi.contracts.v3.ContractBase {
    /** The type of contract */
    contractType: CandidApi.contracts.v3.ContractType;
    /** The UUID of the provider under agreement to the contract */
    contractingProviderId: CandidApi.contracts.v3.ContractingProviderId;
    /** The UUID of the insurance company under agreement to the contract */
    payerUuid: string;
}
