/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CandidApi from "../../../../api/index";
import * as core from "../../../../core";
import { MedicareProviderIdentifier } from "./MedicareProviderIdentifier";
import { MedicaidProviderIdentifier } from "./MedicaidProviderIdentifier";

export const IdentifierValue: core.serialization.Schema<serializers.IdentifierValue.Raw, CandidApi.IdentifierValue> =
    core.serialization
        .union("type", {
            medicare_provider_identifier: MedicareProviderIdentifier,
            medicaid_provider_identifier: MedicaidProviderIdentifier,
        })
        .transform<CandidApi.IdentifierValue>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace IdentifierValue {
    type Raw = IdentifierValue.MedicareProviderIdentifier | IdentifierValue.MedicaidProviderIdentifier;

    interface MedicareProviderIdentifier extends MedicareProviderIdentifier.Raw {
        type: "medicare_provider_identifier";
    }

    interface MedicaidProviderIdentifier extends MedicaidProviderIdentifier.Raw {
        type: "medicaid_provider_identifier";
    }
}
