/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CandidApi from "../../../../api/index";
import * as core from "../../../../core";
import { TagCreate } from "./TagCreate";

export const Tag: core.serialization.ObjectSchema<serializers.Tag.Raw, CandidApi.Tag> = core.serialization
    .object({
        creatorId: core.serialization.property("creator_id", core.serialization.string()),
    })
    .extend(TagCreate);

export declare namespace Tag {
    export interface Raw extends TagCreate.Raw {
        creator_id: string;
    }
}
