/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../..";

export interface InNetworkRenderingProvidersDetail {
    renderingProviders: CandidApi.organizationProviders.v2.OrganizationProviderId[];
    routedPayerUuid: CandidApi.payers.v3.PayerUuid;
    routedBillingProviderId: CandidApi.organizationProviders.v2.OrganizationProviderId;
}
