/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as CandidApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const WriteOffReason: core.serialization.Schema<
    serializers.writeOffs.v1.WriteOffReason.Raw,
    CandidApi.writeOffs.v1.WriteOffReason
> = core.serialization.enum_(["SMALL_BALANCE", "NO_AUTH", "CODING", "CREDENTIALING"]);

export declare namespace WriteOffReason {
    type Raw = "SMALL_BALANCE" | "NO_AUTH" | "CODING" | "CREDENTIALING";
}
