// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../../../index";

/**
 * @example
 *     {}
 */
export interface OrganizationExternalProviderGetMultiRequest {
    limit?: number;
    pageToken?: CandidApi.preEncounter.PageToken;
    /** Defaults to name.family. */
    sortField?: CandidApi.preEncounter.organizationExternalProviders.v1.OrganizationExternalProviderSortField;
    /** Defaults to ascending. */
    sortDirection?: CandidApi.preEncounter.SortDirection;
    npi?: string;
    type?: CandidApi.preEncounter.organizationExternalProviders.v1.OrganizationExternalProviderType;
    firstName?: string;
    lastName?: string;
}
