// This file was auto-generated by Fern from our API Definition.

export const RelatedCausesCode = {
    /**
     * Auto Accident */
    Caa: "AA",
    /**
     * Abuse */
    Cab: "AB",
    /**
     * Another Party Responsible */
    Cap: "AP",
    /**
     * Employment */
    Cem: "EM",
    /**
     * Other Accident */
    Coa: "OA",
    /**
     * Mutually Defined */
    Czz: "ZZ",
} as const;
export type RelatedCausesCode = (typeof RelatedCausesCode)[keyof typeof RelatedCausesCode];
