// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../index";

export interface M2MUserCreateV2 {
    name: string;
    /**
     * Organization to provision the M2M user in. Must be a child organization within the
     * requesting user's enterprise.
     */
    organizationId: CandidApi.OrganizationId;
}
