// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../index";

/**
 * @example
 *     {
 *         type: "human_user_metadata",
 *         firstName: "John",
 *         lastName: "Doe",
 *         email: "john.doe@example.com"
 *     }
 */
export type UserMetadata =
    | CandidApi.users.v2.UserMetadata.MachineUserMetadata
    | CandidApi.users.v2.UserMetadata.HumanUserMetadata;

export namespace UserMetadata {
    export interface MachineUserMetadata extends CandidApi.users.v2.MachineUserMetadata {
        type: "machine_user_metadata";
    }

    export interface HumanUserMetadata extends CandidApi.users.v2.HumanUserMetadata {
        type: "human_user_metadata";
    }
}
