/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../../../../index";

/**
 * @example
 *     {}
 */
export interface AppointmentsGetListRequest {
    /**
     * Defaults to appointment.startTimestamp.
     */
    sortField?: CandidApi.preEncounter.lists.v1.SortFieldString;
    /**
     * Defaults to asc.
     */
    sortDirection?: CandidApi.preEncounter.SortDirection;
    /**
     * Defaults to 100.
     */
    limit?: number;
    pageToken?: CandidApi.preEncounter.PageToken;
    filters?: CandidApi.preEncounter.FilterQueryString;
}
