// This file was auto-generated by Fern from our API Definition.

export const ExternalCauseOfInjuryCodeQualifier = {
    /**
     * International Classification of Diseases Clinical Modification (ICD-9-CM) External Cause of Injury Code (E-codes) */
    Cbn: "BN",
    /**
     * International Classification of Diseases Clinical Modification (ICD-10-CM) External Cause of Injury Code */
    Cabn: "ABN",
} as const;
export type ExternalCauseOfInjuryCodeQualifier =
    (typeof ExternalCauseOfInjuryCodeQualifier)[keyof typeof ExternalCauseOfInjuryCodeQualifier];
