/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../index";

export interface HealthCareCodeInformationGetAllResponse {
    principalDiagnosis?: CandidApi.healthCareCodeInformation.v1.PrincipalDiagnosis;
    admittingDiagnosis?: CandidApi.healthCareCodeInformation.v1.AdmittingDiagnosis;
    patientReasonsForVisit: CandidApi.healthCareCodeInformation.v1.PatientReasonForVisit[];
    externalCausesOfInjury: CandidApi.healthCareCodeInformation.v1.ExternalCauseOfInjury[];
    diagnosisRelatedGroups?: CandidApi.healthCareCodeInformation.v1.DiagnosisRelatedGroup;
    otherDiagnosisInformation: CandidApi.healthCareCodeInformation.v1.OtherDiagnosisInformation[];
    principalProcedure?: CandidApi.healthCareCodeInformation.v1.PrincipalProcedureInformation;
    otherProcedureInformation: CandidApi.healthCareCodeInformation.v1.OtherProcedureInformation[];
    occurrenceSpanInformation: CandidApi.healthCareCodeInformation.v1.OccurrenceSpanInformation[];
    occurrenceInformation: CandidApi.healthCareCodeInformation.v1.OccurrenceInformation[];
    treatmentCodeInformation: CandidApi.healthCareCodeInformation.v1.TreatmentCodeInformation[];
    valueInformation: CandidApi.healthCareCodeInformation.v1.ValueInformation[];
    conditionInformation: CandidApi.healthCareCodeInformation.v1.ConditionInformation[];
}
