/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../index";

export interface HealthCareCodeInformationNew {
    codeListQualifier?: CandidApi.healthCareCodeInformation.v1.CodeListQualifierCode;
    /**
     * A code string whose interpretation depends on the code_list_qualifier being set.
     * You do not need to set this field generally, instead it is provided as advisory
     * context on how this HealthCareCodeInformation's data will be available in reporting.
     */
    industryCode1?: string;
    /**
     * A code string whose interpretation depends on the code_list_qualifier being set.
     * You do not need to set this field generally, instead it is provided as advisory
     * context on how this HealthCareCodeInformation's data will be available in reporting.
     */
    industryCode2?: string;
    /**
     * A code string whose interpretation depends on the code_list_qualifier being set.
     * You do not need to set this field generally, instead it is provided as advisory
     * context on how this HealthCareCodeInformation's data will be available in reporting.
     */
    industryCode3?: string;
    /**
     * A code string whose interpretation depends on the code_list_qualifier being set.
     * You do not need to set this field generally, instead it is provided as advisory
     * context on how this HealthCareCodeInformation's data will be available in reporting.
     */
    industryCode4?: string;
    /**
     * Controls how the date_time_period field is interpreted and is submitted
     * as part of claim process.
     * You do not need to set this field generally, instead it is provided as advisory
     * context on how this HealthCareCodeInformation's data will be available in reporting.
     */
    dateTimePeriodFormatQualifier?: CandidApi.healthCareCodeInformation.v1.DateTimePeriodFormatQualifier;
    /**
     * A string, formatted according to date_time_period_format_qualifier, which
     * ultimately represents the date time period in which an information object
     * is covering.
     * You do not need to set this field generally, instead it is provided as advisory
     * context on how this HealthCareCodeInformation's data will be available in reporting.
     */
    dateTimePeriod?: string;
    /**
     * A decimal used to represent ValueInformation results.
     * You do not need to set this field generally, instead it is provided as advisory
     * context on how this HealthCareCodeInformation's data will be available in reporting.
     */
    monetaryAmount?: CandidApi.Decimal;
    /**
     * You do not need to set this field generally, instead it is provided as advisory
     * context on how this HealthCareCodeInformation's data will be available in reporting.
     */
    quantity?: CandidApi.Decimal;
}
