/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../index";

export interface HealthCareCodeInformationCreate {
    principalDiagnosis?: CandidApi.healthCareCodeInformation.v1.PrincipalDiagnosisNew;
    admittingDiagnosis?: CandidApi.healthCareCodeInformation.v1.AdmittingDiagnosisNew;
    patientReasonsForVisit?: CandidApi.healthCareCodeInformation.v1.PatientReasonForVisitNew[];
    externalCausesOfInjury?: CandidApi.healthCareCodeInformation.v1.ExternalCauseOfInjuryNew[];
    diagnosisRelatedGroups?: CandidApi.healthCareCodeInformation.v1.DiagnosisRelatedGroupNew;
    otherDiagnosisInformation?: CandidApi.healthCareCodeInformation.v1.OtherDiagnosisInformationNew[];
    principalProcedure?: CandidApi.healthCareCodeInformation.v1.PrincipalProcedureInformationNew;
    otherProcedureInformation?: CandidApi.healthCareCodeInformation.v1.OtherProcedureInformationNew[];
    occurrenceSpanInformation?: CandidApi.healthCareCodeInformation.v1.OccurrenceSpanInformationNew[];
    occurrenceInformation?: CandidApi.healthCareCodeInformation.v1.OccurrenceInformationNew[];
    treatmentCodeInformation?: CandidApi.healthCareCodeInformation.v1.TreatmentCodeInformationNew[];
    valueInformation?: CandidApi.healthCareCodeInformation.v1.ValueInformationNew[];
    conditionInformation?: CandidApi.healthCareCodeInformation.v1.ConditionInformationNew[];
}
