// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../index";

/**
 * This corresponds to the BH code qualifier value.
 */
export interface OccurrenceInformationNew extends CandidApi.healthCareCodeInformation.v1.HealthCareCodeInformationNew {
    occurrenceCodeQualifier: CandidApi.healthCareCodeInformation.v1.OccurrenceInformationCodeQualifier;
    occurrenceCode: CandidApi.healthCareCodeInformation.v1.OccurrenceCode;
    /**
     * An [RFC 3339, section 5.6 datetime](https://ijmacd.github.io/rfc3339-iso8601/).
     * For example, 2017-07-21T17:32:28Z.
     * In practice, only the date portion of this is used for claim submission, so
     * midnight time is fine.
     */
    occurrenceDate: CandidApi.healthCareCodeInformation.v1.D8Date;
}
