/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ClaimSubmissionRecordCreateOptional } from "./ClaimSubmissionRecordCreateOptional";

export const ExternalClaimSubmissionCreateOptional: core.serialization.ObjectSchema<
    serializers.claimSubmission.v1.ExternalClaimSubmissionCreateOptional.Raw,
    CandidApi.claimSubmission.v1.ExternalClaimSubmissionCreateOptional
> = core.serialization.object({
    claimCreatedAt: core.serialization.property("claim_created_at", core.serialization.date().optional()),
    patientControlNumber: core.serialization.property("patient_control_number", core.serialization.string().optional()),
    submissionRecords: core.serialization.property(
        "submission_records",
        core.serialization.list(ClaimSubmissionRecordCreateOptional),
    ),
});

export declare namespace ExternalClaimSubmissionCreateOptional {
    export interface Raw {
        claim_created_at?: string | null;
        patient_control_number?: string | null;
        submission_records: ClaimSubmissionRecordCreateOptional.Raw[];
    }
}
