/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../..";

export interface ServiceLineAllocationTarget {
    serviceLineId: CandidApi.ServiceLineId;
    claimId: CandidApi.ClaimId;
    encounterId: CandidApi.EncounterId;
}
