// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../index";

/**
 * A request for a single metric.
 */
export interface MetricQuery {
    metric: CandidApi.dashboarding.v1.MetricName;
    /** Which snapshot to read the metric from. Defaults to `today`. */
    snapshot?: CandidApi.dashboarding.v1.MetricSnapshot;
}
