/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { EncounterId } from "../../../../commons/types/EncounterId";
import { EncounterAttachmentType } from "./EncounterAttachmentType";
import { BaseAttachment } from "./BaseAttachment";

export const EncounterAttachment: core.serialization.ObjectSchema<
    serializers.encounterAttachments.v1.EncounterAttachment.Raw,
    CandidApi.encounterAttachments.v1.EncounterAttachment
> = core.serialization
    .object({
        encounterId: core.serialization.property("encounter_id", EncounterId),
        attachmentType: core.serialization.property("attachment_type", EncounterAttachmentType),
    })
    .extend(BaseAttachment);

export declare namespace EncounterAttachment {
    export interface Raw extends BaseAttachment.Raw {
        encounter_id: EncounterId.Raw;
        attachment_type: EncounterAttachmentType.Raw;
    }
}
