// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";
import { EncounterId } from "../../../../commons/types/EncounterId";
import { UserV2 } from "../../../../users/resources/v2/types/UserV2";
import { BaseAttachment } from "./BaseAttachment";
import { EncounterAttachmentType } from "./EncounterAttachmentType";

export const EncounterAttachment: core.serialization.ObjectSchema<
    serializers.encounterAttachments.v1.EncounterAttachment.Raw,
    CandidApi.encounterAttachments.v1.EncounterAttachment
> = core.serialization
    .object({
        encounterId: core.serialization.property("encounter_id", EncounterId),
        attachmentType: core.serialization.property("attachment_type", EncounterAttachmentType),
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        createdBy: core.serialization.property("created_by", UserV2),
    })
    .extend(BaseAttachment);

export declare namespace EncounterAttachment {
    export interface Raw extends BaseAttachment.Raw {
        encounter_id: EncounterId.Raw;
        attachment_type: EncounterAttachmentType.Raw;
        created_at: string;
        created_by: UserV2.Raw;
    }
}
