// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const EncounterAttachmentType: core.serialization.Schema<
    serializers.encounterAttachments.v1.EncounterAttachmentType.Raw,
    CandidApi.encounterAttachments.v1.EncounterAttachmentType
> = core.serialization.enum_(["DOCUMENTATION", "EOB", "OTHER"]);

export declare namespace EncounterAttachmentType {
    export type Raw = "DOCUMENTATION" | "EOB" | "OTHER";
}
