/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as CandidApi from "../../../../../index";
import * as serializers from "../../../../../../serialization/index";
import urlJoin from "url-join";

export declare namespace V2 {
    export interface Options {
        environment?: core.Supplier<environments.CandidApiEnvironment | environments.CandidApiEnvironmentUrls>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class V2 {
    constructor(protected readonly _options: V2.Options = {}) {}

    /**
     * @param {CandidApi.EncounterId} encounterId
     * @param {CandidApi.encounterProviders.v2.ReferringProviderUpdate} request
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.updateReferringProvider(CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"), {
     *         npi: "string",
     *         taxonomyCode: "string",
     *         address: {
     *             address1: "123 Main St",
     *             address2: "Apt 1",
     *             city: "New York",
     *             state: "NY",
     *             zipCode: "10001",
     *             zipPlusFourCode: "1234"
     *         },
     *         firstName: "string",
     *         lastName: "string",
     *         organizationName: "string"
     *     })
     */
    public async updateReferringProvider(
        encounterId: CandidApi.EncounterId,
        request: CandidApi.encounterProviders.v2.ReferringProviderUpdate,
        requestOptions?: V2.RequestOptions,
    ): Promise<
        core.APIResponse<
            CandidApi.encounterProviders.v2.EncounterProvider,
            CandidApi.encounterProviders.v2.updateReferringProvider.Error
        >
    > {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.EncounterId.jsonOrThrow(encounterId))}`,
            ),
            method: "PATCH",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.encounterProviders.v2.ReferringProviderUpdate.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: serializers.encounterProviders.v2.EncounterProvider.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.updateReferringProvider.Error.Raw)?.errorName
            ) {
                case "HttpRequestValidationsError":
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.updateReferringProvider.Error.parseOrThrow(
                            _response.error.body as serializers.encounterProviders.v2.updateReferringProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.updateReferringProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.EncounterId} encounterId
     * @param {CandidApi.encounterProviders.v2.InitialReferringProviderUpdate} request
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.updateInitialReferringProvider(CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"), {
     *         npi: "string",
     *         taxonomyCode: "string",
     *         address: {
     *             address1: "123 Main St",
     *             address2: "Apt 1",
     *             city: "New York",
     *             state: "NY",
     *             zipCode: "10001",
     *             zipPlusFourCode: "1234"
     *         },
     *         qualifier: "DQ",
     *         firstName: "string",
     *         lastName: "string",
     *         organizationName: "string"
     *     })
     */
    public async updateInitialReferringProvider(
        encounterId: CandidApi.EncounterId,
        request: CandidApi.encounterProviders.v2.InitialReferringProviderUpdate,
        requestOptions?: V2.RequestOptions,
    ): Promise<
        core.APIResponse<
            CandidApi.encounterProviders.v2.EncounterProvider,
            CandidApi.encounterProviders.v2.updateInitialReferringProvider.Error
        >
    > {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.EncounterId.jsonOrThrow(encounterId))}/initial-referring-provider`,
            ),
            method: "PATCH",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.encounterProviders.v2.InitialReferringProviderUpdate.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: serializers.encounterProviders.v2.EncounterProvider.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.updateInitialReferringProvider.Error.Raw)
                    ?.errorName
            ) {
                case "HttpRequestValidationsError":
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.updateInitialReferringProvider.Error.parseOrThrow(
                            _response.error
                                .body as serializers.encounterProviders.v2.updateInitialReferringProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.updateInitialReferringProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.EncounterId} encounterId
     * @param {CandidApi.encounterProviders.v2.SupervisingProviderUpdate} request
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.updateSupervisingProvider(CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"), {
     *         npi: "string",
     *         taxonomyCode: "string",
     *         address: {
     *             address1: "123 Main St",
     *             address2: "Apt 1",
     *             city: "New York",
     *             state: "NY",
     *             zipCode: "10001",
     *             zipPlusFourCode: "1234"
     *         },
     *         firstName: "string",
     *         lastName: "string",
     *         organizationName: "string"
     *     })
     */
    public async updateSupervisingProvider(
        encounterId: CandidApi.EncounterId,
        request: CandidApi.encounterProviders.v2.SupervisingProviderUpdate,
        requestOptions?: V2.RequestOptions,
    ): Promise<
        core.APIResponse<
            CandidApi.encounterProviders.v2.EncounterProvider,
            CandidApi.encounterProviders.v2.updateSupervisingProvider.Error
        >
    > {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.EncounterId.jsonOrThrow(encounterId))}/supervising-provider`,
            ),
            method: "PATCH",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.encounterProviders.v2.SupervisingProviderUpdate.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: serializers.encounterProviders.v2.EncounterProvider.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.updateSupervisingProvider.Error.Raw)
                    ?.errorName
            ) {
                case "HttpRequestValidationsError":
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.updateSupervisingProvider.Error.parseOrThrow(
                            _response.error
                                .body as serializers.encounterProviders.v2.updateSupervisingProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.updateSupervisingProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.ServiceLineId} serviceLineId
     * @param {CandidApi.encounterProviders.v2.OrderingProviderUpdate} request
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.updateOrderingProvider(CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"), {
     *         npi: "string",
     *         taxonomyCode: "string",
     *         address: {
     *             address1: "123 Main St",
     *             address2: "Apt 1",
     *             city: "New York",
     *             state: "NY",
     *             zipCode: "10001",
     *             zipPlusFourCode: "1234"
     *         },
     *         firstName: "string",
     *         lastName: "string",
     *         organizationName: "string"
     *     })
     */
    public async updateOrderingProvider(
        serviceLineId: CandidApi.ServiceLineId,
        request: CandidApi.encounterProviders.v2.OrderingProviderUpdate,
        requestOptions?: V2.RequestOptions,
    ): Promise<
        core.APIResponse<
            CandidApi.encounterProviders.v2.EncounterProvider,
            CandidApi.encounterProviders.v2.updateOrderingProvider.Error
        >
    > {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.ServiceLineId.jsonOrThrow(serviceLineId))}/ordering-provider`,
            ),
            method: "PATCH",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.encounterProviders.v2.OrderingProviderUpdate.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: serializers.encounterProviders.v2.EncounterProvider.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.updateOrderingProvider.Error.Raw)?.errorName
            ) {
                case "HttpRequestValidationsError":
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.updateOrderingProvider.Error.parseOrThrow(
                            _response.error.body as serializers.encounterProviders.v2.updateOrderingProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.updateOrderingProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.EncounterId} encounterId
     * @param {CandidApi.encounterProviders.v2.ReferringProvider} request
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.createReferringProvider(CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"), {
     *         npi: "string",
     *         taxonomyCode: "string",
     *         address: {
     *             address1: "123 Main St",
     *             address2: "Apt 1",
     *             city: "New York",
     *             state: "NY",
     *             zipCode: "10001",
     *             zipPlusFourCode: "1234"
     *         },
     *         firstName: "string",
     *         lastName: "string",
     *         organizationName: "string"
     *     })
     */
    public async createReferringProvider(
        encounterId: CandidApi.EncounterId,
        request: CandidApi.encounterProviders.v2.ReferringProvider,
        requestOptions?: V2.RequestOptions,
    ): Promise<
        core.APIResponse<
            CandidApi.encounterProviders.v2.EncounterProvider,
            CandidApi.encounterProviders.v2.createReferringProvider.Error
        >
    > {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.EncounterId.jsonOrThrow(encounterId))}/create-referring-provider`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.encounterProviders.v2.ReferringProvider.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: serializers.encounterProviders.v2.EncounterProvider.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.createReferringProvider.Error.Raw)?.errorName
            ) {
                case "EntityConflictError":
                case "HttpRequestValidationsError":
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.createReferringProvider.Error.parseOrThrow(
                            _response.error.body as serializers.encounterProviders.v2.createReferringProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.createReferringProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.EncounterId} encounterId
     * @param {CandidApi.encounterProviders.v2.InitialReferringProvider} request
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.createInitialReferringProvider(CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"), {
     *         npi: "string",
     *         taxonomyCode: "string",
     *         address: {
     *             address1: "123 Main St",
     *             address2: "Apt 1",
     *             city: "New York",
     *             state: "NY",
     *             zipCode: "10001",
     *             zipPlusFourCode: "1234"
     *         },
     *         qualifier: "DQ",
     *         firstName: "string",
     *         lastName: "string",
     *         organizationName: "string"
     *     })
     */
    public async createInitialReferringProvider(
        encounterId: CandidApi.EncounterId,
        request: CandidApi.encounterProviders.v2.InitialReferringProvider,
        requestOptions?: V2.RequestOptions,
    ): Promise<
        core.APIResponse<
            CandidApi.encounterProviders.v2.EncounterProvider,
            CandidApi.encounterProviders.v2.createInitialReferringProvider.Error
        >
    > {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.EncounterId.jsonOrThrow(encounterId))}/create-initial-referring-provider`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.encounterProviders.v2.InitialReferringProvider.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: serializers.encounterProviders.v2.EncounterProvider.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.createInitialReferringProvider.Error.Raw)
                    ?.errorName
            ) {
                case "EntityConflictError":
                case "UnprocessableEntityError":
                case "HttpRequestValidationsError":
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.createInitialReferringProvider.Error.parseOrThrow(
                            _response.error
                                .body as serializers.encounterProviders.v2.createInitialReferringProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.createInitialReferringProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.EncounterId} encounterId
     * @param {CandidApi.encounterProviders.v2.SupervisingProvider} request
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.createSupervisingProvider(CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"), {
     *         npi: "string",
     *         taxonomyCode: "string",
     *         address: {
     *             address1: "123 Main St",
     *             address2: "Apt 1",
     *             city: "New York",
     *             state: "NY",
     *             zipCode: "10001",
     *             zipPlusFourCode: "1234"
     *         },
     *         firstName: "string",
     *         lastName: "string",
     *         organizationName: "string"
     *     })
     */
    public async createSupervisingProvider(
        encounterId: CandidApi.EncounterId,
        request: CandidApi.encounterProviders.v2.SupervisingProvider,
        requestOptions?: V2.RequestOptions,
    ): Promise<
        core.APIResponse<
            CandidApi.encounterProviders.v2.EncounterProvider,
            CandidApi.encounterProviders.v2.createSupervisingProvider.Error
        >
    > {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.EncounterId.jsonOrThrow(encounterId))}/create-supervising-provider`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.encounterProviders.v2.SupervisingProvider.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: serializers.encounterProviders.v2.EncounterProvider.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.createSupervisingProvider.Error.Raw)
                    ?.errorName
            ) {
                case "EntityConflictError":
                case "HttpRequestValidationsError":
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.createSupervisingProvider.Error.parseOrThrow(
                            _response.error
                                .body as serializers.encounterProviders.v2.createSupervisingProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.createSupervisingProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.ServiceLineId} serviceLineId
     * @param {CandidApi.encounterProviders.v2.OrderingProvider} request
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.createOrderingProvider(CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"), {
     *         npi: "string",
     *         taxonomyCode: "string",
     *         address: {
     *             address1: "123 Main St",
     *             address2: "Apt 1",
     *             city: "New York",
     *             state: "NY",
     *             zipCode: "10001",
     *             zipPlusFourCode: "1234"
     *         },
     *         firstName: "string",
     *         lastName: "string",
     *         organizationName: "string"
     *     })
     */
    public async createOrderingProvider(
        serviceLineId: CandidApi.ServiceLineId,
        request: CandidApi.encounterProviders.v2.OrderingProvider,
        requestOptions?: V2.RequestOptions,
    ): Promise<
        core.APIResponse<
            CandidApi.encounterProviders.v2.EncounterProvider,
            CandidApi.encounterProviders.v2.createOrderingProvider.Error
        >
    > {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.ServiceLineId.jsonOrThrow(serviceLineId))}/create-ordering-provider`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.encounterProviders.v2.OrderingProvider.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: serializers.encounterProviders.v2.EncounterProvider.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.createOrderingProvider.Error.Raw)?.errorName
            ) {
                case "EntityConflictError":
                case "HttpRequestValidationsError":
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.createOrderingProvider.Error.parseOrThrow(
                            _response.error.body as serializers.encounterProviders.v2.createOrderingProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.createOrderingProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.EncounterId} encounterId
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.deleteReferringProvider(CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"))
     */
    public async deleteReferringProvider(
        encounterId: CandidApi.EncounterId,
        requestOptions?: V2.RequestOptions,
    ): Promise<core.APIResponse<void, CandidApi.encounterProviders.v2.deleteReferringProvider.Error>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.EncounterId.jsonOrThrow(encounterId))}/referring-provider`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: undefined,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.deleteReferringProvider.Error.Raw)?.errorName
            ) {
                case "EntityNotFoundError":
                case "EntityConflictError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.deleteReferringProvider.Error.parseOrThrow(
                            _response.error.body as serializers.encounterProviders.v2.deleteReferringProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.deleteReferringProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.EncounterId} encounterId
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.deleteInitialReferringProvider(CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"))
     */
    public async deleteInitialReferringProvider(
        encounterId: CandidApi.EncounterId,
        requestOptions?: V2.RequestOptions,
    ): Promise<core.APIResponse<void, CandidApi.encounterProviders.v2.deleteInitialReferringProvider.Error>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.EncounterId.jsonOrThrow(encounterId))}/initial-referring-provider`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: undefined,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.deleteInitialReferringProvider.Error.Raw)
                    ?.errorName
            ) {
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.deleteInitialReferringProvider.Error.parseOrThrow(
                            _response.error
                                .body as serializers.encounterProviders.v2.deleteInitialReferringProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.deleteInitialReferringProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.EncounterId} encounterId
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.deleteSupervisingProvider(CandidApi.EncounterId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"))
     */
    public async deleteSupervisingProvider(
        encounterId: CandidApi.EncounterId,
        requestOptions?: V2.RequestOptions,
    ): Promise<core.APIResponse<void, CandidApi.encounterProviders.v2.deleteSupervisingProvider.Error>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.EncounterId.jsonOrThrow(encounterId))}/supervising-provider`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: undefined,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.deleteSupervisingProvider.Error.Raw)
                    ?.errorName
            ) {
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.deleteSupervisingProvider.Error.parseOrThrow(
                            _response.error
                                .body as serializers.encounterProviders.v2.deleteSupervisingProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.deleteSupervisingProvider.Error._unknown(_response.error),
        };
    }

    /**
     * @param {CandidApi.ServiceLineId} serviceLineId
     * @param {V2.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.encounterProviders.v2.deleteOrderingProvider(CandidApi.ServiceLineId("d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32"))
     */
    public async deleteOrderingProvider(
        serviceLineId: CandidApi.ServiceLineId,
        requestOptions?: V2.RequestOptions,
    ): Promise<core.APIResponse<void, CandidApi.encounterProviders.v2.deleteOrderingProvider.Error>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.CandidApiEnvironment.Production
                    ).candidApi,
                `/api/encounter-providers/v2/${encodeURIComponent(serializers.ServiceLineId.jsonOrThrow(serviceLineId))}/ordering-provider`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "candidhealth",
                "X-Fern-SDK-Version": "0.45.0",
                "User-Agent": "candidhealth/0.45.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                ok: true,
                body: undefined,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (
                (_response.error.body as serializers.encounterProviders.v2.deleteOrderingProvider.Error.Raw)?.errorName
            ) {
                case "EntityNotFoundError":
                    return {
                        ok: false,
                        error: serializers.encounterProviders.v2.deleteOrderingProvider.Error.parseOrThrow(
                            _response.error.body as serializers.encounterProviders.v2.deleteOrderingProvider.Error.Raw,
                            {
                                unrecognizedObjectKeys: "passthrough",
                                allowUnrecognizedUnionMembers: true,
                                allowUnrecognizedEnumValues: true,
                                breadcrumbsPrefix: ["response"],
                            },
                        ),
                    };
            }
        }

        return {
            ok: false,
            error: CandidApi.encounterProviders.v2.deleteOrderingProvider.Error._unknown(_response.error),
        };
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
