// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const ErrorBase5Xx: core.serialization.ObjectSchema<
    serializers.preEncounter.ErrorBase5Xx.Raw,
    CandidApi.preEncounter.ErrorBase5Xx
> = core.serialization.object({
    message: core.serialization.string(),
    data: core.serialization.unknown().optional(),
});

export declare namespace ErrorBase5Xx {
    export interface Raw {
        message: string;
        data?: unknown | null;
    }
}
