/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const TagId: core.serialization.Schema<serializers.preEncounter.TagId.Raw, CandidApi.preEncounter.TagId> =
    core.serialization.string().transform({
        transform: CandidApi.preEncounter.TagId,
        untransform: (value) => value,
    });

export declare namespace TagId {
    type Raw = string;
}
