// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../index";

export interface IndividualBaseOptional {
    firstName?: string;
    lastName?: string;
    gender?: CandidApi.Gender;
}
