// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../index";

export interface PatientClinicalTrialInfoCreate {
    clinicalTrialArm?: string;
    clinicalTrialId: CandidApi.ClinicalTrialId;
}
