// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { Date_ } from "../../commons/types/Date_";

export const EraBase: core.serialization.ObjectSchema<serializers.EraBase.Raw, CandidApi.EraBase> =
    core.serialization.object({
        checkNumber: core.serialization.property("check_number", core.serialization.string()),
        checkDate: core.serialization.property("check_date", Date_),
    });

export declare namespace EraBase {
    export interface Raw {
        check_number: string;
        check_date: Date_.Raw;
    }
}
