/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../index";

export interface UniversalEncounterCreateBase extends CandidApi.encounters.v4.EncounterBase {
    /** Contains the identification information of the individual receiving medical services. */
    patient: CandidApi.PatientCreate;
    /**
     * The final provider who referred the services that were rendered.
     * All physicians who order services or refer Medicare beneficiaries must
     * report this data.
     */
    referringProvider?: CandidApi.encounterProviders.v2.ReferringProvider;
    /**
     * The second iteration of Loop ID-2310 on an 837P form. Use code "P3 - Primary Care Provider" in this loop to
     * indicate the initial referral from the primary care provider or whatever provider wrote the initial referral for this patient's episode of care being billed/reported in this transaction.
     * Not used in an 837i claim
     */
    initialReferringProvider?: CandidApi.encounterProviders.v2.InitialReferringProvider;
    /** Required when the rendering provider is supervised by a physician. If not required by this implementation guide, do not send. */
    supervisingProvider?: CandidApi.encounterProviders.v2.SupervisingProvider;
    /** Encounter Service facility is typically the location a medical service was rendered, such as a provider office or hospital. For telehealth, service facility can represent the provider's location when the service was delivered (e.g., home), or the location where an in-person visit would have taken place, whichever is easier to identify. If the provider is in-network, service facility may be defined in payer contracts. Box 32 on the CMS-1500 claim form. There is no equivalent on the paper UB-04 claim form, but this field is equivalent to Loop 2310E Service Facility Location details on an 837i form, and is used when this is different to the entity identified as the Billing Provider. Note that for an in-network claim to be successfully adjudicated, the service facility address listed */
    serviceFacility?: CandidApi.EncounterServiceFacilityBase;
    /**
     * Subscriber_primary is required when responsible_party is INSURANCE_PAY (i.e. when the claim should be billed to insurance).
     * These are not required fields when responsible_party is SELF_PAY (i.e. when the claim should be billed to the patient).
     * However, if you collect this for patients, even self-pay, we recommend including it when sending encounters to Candid.
     * Note: Cash Pay is no longer a valid payer_id in v4, please use responsible party to define self-pay claims.
     */
    subscriberPrimary?: CandidApi.SubscriberCreate;
    /** Please always include this when you have it, even for self-pay claims. */
    subscriberSecondary?: CandidApi.SubscriberCreate;
    /** Please always include this when you have it, even for self-pay claims. */
    subscriberTertiary?: CandidApi.SubscriberCreate;
    /** Box 23 on the CMS-1500 claim form or Form Locator 63 on a UB-04 claim form. */
    priorAuthorizationNumber?: CandidApi.encounters.v4.PriorAuthorizationNumber;
    /** Defines the party to be billed with the initial balance owed on the claim. */
    responsibleParty: CandidApi.encounters.v4.ResponsiblePartyType;
    /** Holds a collection of clinical observations made by healthcare providers during patient encounters. Please note that medical records for appeals should be sent using the Encounter Attachments API. */
    clinicalNotes?: CandidApi.encounters.v4.ClinicalNoteCategoryCreate[];
    /**
     * Spot to store misc, human-readable, notes about this encounter to be used
     * in the billing process.
     */
    billingNotes?: CandidApi.billingNotes.v2.BillingNoteBase[];
    patientHistories?: CandidApi.encounters.v4.PatientHistoryCategory[];
    /** Personal and contact info for the guarantor of the patient responsibility. */
    guarantor?: CandidApi.guarantor.v1.GuarantorCreate;
    /**
     * To be included for claims that have been submitted outside of Candid.
     * Candid supports posting remits and payments to these claims and working them in-platform (e.g. editing, resubmitting).
     */
    externalClaimSubmission?: CandidApi.claimSubmission.v1.ExternalClaimSubmissionCreate;
    /** Names of tags that should be on the encounter. */
    tagIds?: CandidApi.TagId[];
    /**
     * Key-value pairs that must adhere to a schema created via the Custom Schema API. Multiple schema
     * instances cannot be created for the same schema on an encounter.
     */
    schemaInstances?: CandidApi.customSchemas.v1.SchemaInstance[];
    /** Refers to REF*9F on the 837p and 837i. Value cannot be greater than 50 characters. */
    referralNumber?: string;
    /** Refers to Box 24H on the CMS1500 form and Loop 2300 CRC - EPSDT Referral on the 837P and 837i form */
    epsdtReferral?: CandidApi.encounters.v4.EpsdtReferral;
    /** Refers to Loop 2300 - Segment PWK on the 837P and 837i forms. No more than 10 entries are permitted. */
    claimSupplementalInformation?: CandidApi.encounters.v4.ClaimSupplementalInformation[];
    /** When Medicaid is billed as the secondary payer the Carrier Code is used to identify the primary payer. This is required for certain states. */
    secondaryPayerCarrierCode?: string;
}
