// This file was auto-generated by Fern from our API Definition.

/** The name of a dimension. */
export const DimensionName = {
    PayerUuid: "payer_uuid",
    OrganizationBillingProviderId: "organization_billing_provider_id",
    CptCode: "cpt_code",
} as const;
export type DimensionName = (typeof DimensionName)[keyof typeof DimensionName];
