/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../..";

export interface PayerThresholdsPage extends CandidApi.ResourcePage {
    payerThresholds: Record<CandidApi.payers.v3.PayerUuid, CandidApi.feeSchedules.v3.PayerThreshold>;
}
