/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../..";

export type WriteOff = CandidApi.writeOffs.v1.WriteOff.Patient | CandidApi.writeOffs.v1.WriteOff.Insurance;

export declare namespace WriteOff {
    interface Patient extends CandidApi.writeOffs.v1.PatientWriteOff {
        type: "patient";
    }

    interface Insurance extends CandidApi.writeOffs.v1.InsuranceWriteOff {
        type: "insurance";
    }
}
