/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CandidApi } from "";
import * as core from "../../../../core";

export const ServiceFacilityId: core.serialization.Schema<
    serializers.ServiceFacilityId.Raw,
    CandidApi.ServiceFacilityId
> = core.serialization.string();

export declare namespace ServiceFacilityId {
    type Raw = string;
}
