/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../index";

export type ThirdPartyPayerCategoryUpdate =
    | CandidApi.thirdPartyPayers.v1.ThirdPartyPayerCategoryUpdate.Remove
    /**
     * Max 255 characters allowed */
    | CandidApi.thirdPartyPayers.v1.ThirdPartyPayerCategoryUpdate.Set;

export declare namespace ThirdPartyPayerCategoryUpdate {
    interface Remove {
        type: "remove";
    }

    interface Set {
        type: "set";
        value: string;
    }
}
