// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const QueueAddedMetadata: core.serialization.ObjectSchema<
    serializers.billingNotes.v2.QueueAddedMetadata.Raw,
    CandidApi.billingNotes.v2.QueueAddedMetadata
> = core.serialization.object({
    queueId: core.serialization.property("queue_id", core.serialization.string()),
    queueName: core.serialization.property("queue_name", core.serialization.string()),
});

export declare namespace QueueAddedMetadata {
    export interface Raw {
        queue_id: string;
        queue_name: string;
    }
}
