/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../..";

export type InsuranceTypes =
    | CandidApi.contracts.v2.InsuranceTypes.AllApply
    | CandidApi.contracts.v2.InsuranceTypes.NoneApply
    | CandidApi.contracts.v2.InsuranceTypes.TheseApply;

export declare namespace InsuranceTypes {
    interface AllApply {
        type: "allApply";
    }

    interface NoneApply {
        type: "noneApply";
    }

    interface TheseApply {
        type: "theseApply";
        value: CandidApi.InsuranceTypeCode[];
    }
}
