// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../index";

/**
 * Update type for the treating provider with optional address fields. Used in contexts where address fields may be partially provided.
 */
export interface TreatingProviderUpdateWithOptionalAddress {
    firstName?: string;
    lastName?: string;
    /**
     * A National Provider Identifier is a unique 10-digit identification
     * number issued to health care providers in the United States
     */
    npi?: string;
    taxonomyCode?: string;
    address?: CandidApi.StreetAddressLongZipOptional;
    /** The license type of the treating provider (e.g., MD, NP, PA, LCSW). */
    licenseType?: CandidApi.organizationProviders.v2.LicenseType;
}
