/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as CandidApi from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { RateId } from "../../../../../commons/types/RateId";

export const HardDeleteRatesByIdsRequest: core.serialization.Schema<
    serializers.feeSchedules.v3.HardDeleteRatesByIdsRequest.Raw,
    CandidApi.feeSchedules.v3.HardDeleteRatesByIdsRequest
> = core.serialization.object({
    rateIds: core.serialization.property("rate_ids", core.serialization.list(RateId)),
});

export declare namespace HardDeleteRatesByIdsRequest {
    export interface Raw {
        rate_ids: RateId.Raw[];
    }
}
