/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../../index";

export type ThirdPartyPayerRefundId = string & {
    thirdPartyPayerRefunds_v1_ThirdPartyPayerRefundId: void;
};

export function ThirdPartyPayerRefundId(value: string): CandidApi.thirdPartyPayerRefunds.v1.ThirdPartyPayerRefundId {
    return value as unknown as CandidApi.thirdPartyPayerRefunds.v1.ThirdPartyPayerRefundId;
}
