// This file was auto-generated by Fern from our API Definition.

export const AttachmentInclusion = {
    NotIncluded: "not_included",
    IncludedOnNextSubmission: "included_on_next_submission",
    IncludedOnAllSubmissions: "included_on_all_submissions",
} as const;
export type AttachmentInclusion = (typeof AttachmentInclusion)[keyof typeof AttachmentInclusion];
