/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as CandidApi from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { EligibilityCheckMetadata } from "./EligibilityCheckMetadata";
import { EligibilityCheck } from "./EligibilityCheck";

export const CoverageEligibilityCheckResponse: core.serialization.ObjectSchema<
    serializers.preEncounter.coverages.v1.CoverageEligibilityCheckResponse.Raw,
    CandidApi.preEncounter.coverages.v1.CoverageEligibilityCheckResponse
> = core.serialization.object({
    metadata: EligibilityCheckMetadata,
    check: EligibilityCheck.optional(),
});

export declare namespace CoverageEligibilityCheckResponse {
    export interface Raw {
        metadata: EligibilityCheckMetadata.Raw;
        check?: EligibilityCheck.Raw | null;
    }
}
