/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const ThirdPartyPayerDescriptionUpdate: core.serialization.Schema<
    serializers.thirdPartyPayers.v1.ThirdPartyPayerDescriptionUpdate.Raw,
    CandidApi.thirdPartyPayers.v1.ThirdPartyPayerDescriptionUpdate
> = core.serialization
    .union("type", {
        remove: core.serialization.object({}),
        set: core.serialization.object({
            value: core.serialization.string(),
        }),
    })
    .transform<CandidApi.thirdPartyPayers.v1.ThirdPartyPayerDescriptionUpdate>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace ThirdPartyPayerDescriptionUpdate {
    type Raw = ThirdPartyPayerDescriptionUpdate.Remove | ThirdPartyPayerDescriptionUpdate.Set;

    interface Remove {
        type: "remove";
    }

    interface Set {
        type: "set";
        value: string;
    }
}
