// This file was auto-generated by Fern from our API Definition.

export const CoverageType = {
    Primary: "primary",
    Secondary: "secondary",
    Tertiary: "tertiary",
} as const;
export type CoverageType = (typeof CoverageType)[keyof typeof CoverageType];
