// This file was auto-generated by Fern from our API Definition.

export const ReferralType = {
    Directed: "DIRECTED",
    Rotation: "ROTATION",
    Overnight: "OVERNIGHT",
} as const;
export type ReferralType = (typeof ReferralType)[keyof typeof ReferralType];
