/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SupportState = "NOT_SUPPORTED" | "SUPPORTED_ENROLLMENT_NOT_REQUIRED" | "SUPPORTED_ENROLLMENT_REQUIRED";
export const SupportState = {
    NotSupported: "NOT_SUPPORTED",
    SupportedEnrollmentNotRequired: "SUPPORTED_ENROLLMENT_NOT_REQUIRED",
    SupportedEnrollmentRequired: "SUPPORTED_ENROLLMENT_REQUIRED",
} as const;
