// This file was auto-generated by Fern from our API Definition.

export const EpsdtReferralConditionIndicatorCode = {
    Av: "AV",
    Nu: "NU",
    S2: "S2",
    St: "ST",
} as const;
export type EpsdtReferralConditionIndicatorCode =
    (typeof EpsdtReferralConditionIndicatorCode)[keyof typeof EpsdtReferralConditionIndicatorCode];
