// This file was auto-generated by Fern from our API Definition.

export const ReportTransmissionCode = {
    /**
     * Available on Request at Provider Site */
    Caa: "AA",
    /**
     * By Mail */
    Cbm: "BM",
    /**
     * Electronically Only */
    Cel: "EL",
    /**
     * By Fax */
    Cfx: "FX",
} as const;
export type ReportTransmissionCode = (typeof ReportTransmissionCode)[keyof typeof ReportTransmissionCode];
