/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CandidApi } from "";

export interface StreetAddressShortZip extends CandidApi.StreetAddressBase {
    /** 4-digit zip add-on code https://en.wikipedia.org/wiki/ZIP_Code#ZIP+4 */
    zipPlusFourCode?: string;
}
