// This file was auto-generated by Fern from our API Definition.

import { AuthClient } from "./api/resources/auth/client/Client";
import { BillingNotesClient } from "./api/resources/billingNotes/client/Client";
import { ChargeCaptureClient } from "./api/resources/chargeCapture/client/Client";
import { ChargeCaptureBundlesClient } from "./api/resources/chargeCaptureBundles/client/Client";
import { ContractsClient } from "./api/resources/contracts/client/Client";
import { CredentialingClient } from "./api/resources/credentialing/client/Client";
import { CustomSchemasClient } from "./api/resources/customSchemas/client/Client";
import { DiagnosesClient } from "./api/resources/diagnoses/client/Client";
import { EligibilityClient } from "./api/resources/eligibility/client/Client";
import { EncounterAttachmentsClient } from "./api/resources/encounterAttachments/client/Client";
import { EncounterProvidersClient } from "./api/resources/encounterProviders/client/Client";
import { EncounterSupplementalInformationClient } from "./api/resources/encounterSupplementalInformation/client/Client";
import { EncountersClient } from "./api/resources/encounters/client/Client";
import { EventsClient } from "./api/resources/events/client/Client";
import { ExportsClient } from "./api/resources/exports/client/Client";
import { ExternalPaymentAccountConfigClient } from "./api/resources/externalPaymentAccountConfig/client/Client";
import { FeeSchedulesClient } from "./api/resources/feeSchedules/client/Client";
import { GuarantorClient } from "./api/resources/guarantor/client/Client";
import { HealthCareCodeInformationClient } from "./api/resources/healthCareCodeInformation/client/Client";
import { ImportInvoiceClient } from "./api/resources/importInvoice/client/Client";
import { InsuranceAdjudicationsClient } from "./api/resources/insuranceAdjudications/client/Client";
import { InsuranceRefundsClient } from "./api/resources/insuranceRefunds/client/Client";
import { MedicationDispenseClient } from "./api/resources/medicationDispense/client/Client";
import { NonInsurancePayerPaymentsClient } from "./api/resources/nonInsurancePayerPayments/client/Client";
import { NonInsurancePayerRefundsClient } from "./api/resources/nonInsurancePayerRefunds/client/Client";
import { NonInsurancePayersClient } from "./api/resources/nonInsurancePayers/client/Client";
import { OrganizationProvidersClient } from "./api/resources/organizationProviders/client/Client";
import { OrganizationServiceFacilitiesClient } from "./api/resources/organizationServiceFacilities/client/Client";
import { PatientArClient } from "./api/resources/patientAr/client/Client";
import { PatientPaymentsClient } from "./api/resources/patientPayments/client/Client";
import { PatientRefundsClient } from "./api/resources/patientRefunds/client/Client";
import { PayerPlanGroupsClient } from "./api/resources/payerPlanGroups/client/Client";
import { PayersClient } from "./api/resources/payers/client/Client";
import { PreEncounterClient } from "./api/resources/preEncounter/client/Client";
import { ServiceLinesClient } from "./api/resources/serviceLines/client/Client";
import { SuperbillsClient } from "./api/resources/superbills/client/Client";
import { TasksClient } from "./api/resources/tasks/client/Client";
import { WriteOffsClient } from "./api/resources/writeOffs/client/Client";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient";

export declare namespace CandidApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CandidApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CandidApiClient.Options>;
    protected _auth: AuthClient | undefined;
    protected _billingNotes: BillingNotesClient | undefined;
    protected _chargeCaptureBundles: ChargeCaptureBundlesClient | undefined;
    protected _chargeCapture: ChargeCaptureClient | undefined;
    protected _contracts: ContractsClient | undefined;
    protected _credentialing: CredentialingClient | undefined;
    protected _customSchemas: CustomSchemasClient | undefined;
    protected _eligibility: EligibilityClient | undefined;
    protected _encounterAttachments: EncounterAttachmentsClient | undefined;
    protected _encounterProviders: EncounterProvidersClient | undefined;
    protected _encounterSupplementalInformation: EncounterSupplementalInformationClient | undefined;
    protected _encounters: EncountersClient | undefined;
    protected _events: EventsClient | undefined;
    protected _exports: ExportsClient | undefined;
    protected _externalPaymentAccountConfig: ExternalPaymentAccountConfigClient | undefined;
    protected _feeSchedules: FeeSchedulesClient | undefined;
    protected _guarantor: GuarantorClient | undefined;
    protected _healthCareCodeInformation: HealthCareCodeInformationClient | undefined;
    protected _importInvoice: ImportInvoiceClient | undefined;
    protected _insuranceAdjudications: InsuranceAdjudicationsClient | undefined;
    protected _insuranceRefunds: InsuranceRefundsClient | undefined;
    protected _medicationDispense: MedicationDispenseClient | undefined;
    protected _nonInsurancePayerPayments: NonInsurancePayerPaymentsClient | undefined;
    protected _nonInsurancePayerRefunds: NonInsurancePayerRefundsClient | undefined;
    protected _nonInsurancePayers: NonInsurancePayersClient | undefined;
    protected _organizationProviders: OrganizationProvidersClient | undefined;
    protected _organizationServiceFacilities: OrganizationServiceFacilitiesClient | undefined;
    protected _patientAr: PatientArClient | undefined;
    protected _patientPayments: PatientPaymentsClient | undefined;
    protected _patientRefunds: PatientRefundsClient | undefined;
    protected _payerPlanGroups: PayerPlanGroupsClient | undefined;
    protected _payers: PayersClient | undefined;
    protected _serviceLines: ServiceLinesClient | undefined;
    protected _superbills: SuperbillsClient | undefined;
    protected _tasks: TasksClient | undefined;
    protected _writeOffs: WriteOffsClient | undefined;
    protected _preEncounter: PreEncounterClient | undefined;
    protected _diagnoses: DiagnosesClient | undefined;

    constructor(options: CandidApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get auth(): AuthClient {
        return (this._auth ??= new AuthClient(this._options));
    }

    public get billingNotes(): BillingNotesClient {
        return (this._billingNotes ??= new BillingNotesClient(this._options));
    }

    public get chargeCaptureBundles(): ChargeCaptureBundlesClient {
        return (this._chargeCaptureBundles ??= new ChargeCaptureBundlesClient(this._options));
    }

    public get chargeCapture(): ChargeCaptureClient {
        return (this._chargeCapture ??= new ChargeCaptureClient(this._options));
    }

    public get contracts(): ContractsClient {
        return (this._contracts ??= new ContractsClient(this._options));
    }

    public get credentialing(): CredentialingClient {
        return (this._credentialing ??= new CredentialingClient(this._options));
    }

    public get customSchemas(): CustomSchemasClient {
        return (this._customSchemas ??= new CustomSchemasClient(this._options));
    }

    public get eligibility(): EligibilityClient {
        return (this._eligibility ??= new EligibilityClient(this._options));
    }

    public get encounterAttachments(): EncounterAttachmentsClient {
        return (this._encounterAttachments ??= new EncounterAttachmentsClient(this._options));
    }

    public get encounterProviders(): EncounterProvidersClient {
        return (this._encounterProviders ??= new EncounterProvidersClient(this._options));
    }

    public get encounterSupplementalInformation(): EncounterSupplementalInformationClient {
        return (this._encounterSupplementalInformation ??= new EncounterSupplementalInformationClient(this._options));
    }

    public get encounters(): EncountersClient {
        return (this._encounters ??= new EncountersClient(this._options));
    }

    public get events(): EventsClient {
        return (this._events ??= new EventsClient(this._options));
    }

    public get exports(): ExportsClient {
        return (this._exports ??= new ExportsClient(this._options));
    }

    public get externalPaymentAccountConfig(): ExternalPaymentAccountConfigClient {
        return (this._externalPaymentAccountConfig ??= new ExternalPaymentAccountConfigClient(this._options));
    }

    public get feeSchedules(): FeeSchedulesClient {
        return (this._feeSchedules ??= new FeeSchedulesClient(this._options));
    }

    public get guarantor(): GuarantorClient {
        return (this._guarantor ??= new GuarantorClient(this._options));
    }

    public get healthCareCodeInformation(): HealthCareCodeInformationClient {
        return (this._healthCareCodeInformation ??= new HealthCareCodeInformationClient(this._options));
    }

    public get importInvoice(): ImportInvoiceClient {
        return (this._importInvoice ??= new ImportInvoiceClient(this._options));
    }

    public get insuranceAdjudications(): InsuranceAdjudicationsClient {
        return (this._insuranceAdjudications ??= new InsuranceAdjudicationsClient(this._options));
    }

    public get insuranceRefunds(): InsuranceRefundsClient {
        return (this._insuranceRefunds ??= new InsuranceRefundsClient(this._options));
    }

    public get medicationDispense(): MedicationDispenseClient {
        return (this._medicationDispense ??= new MedicationDispenseClient(this._options));
    }

    public get nonInsurancePayerPayments(): NonInsurancePayerPaymentsClient {
        return (this._nonInsurancePayerPayments ??= new NonInsurancePayerPaymentsClient(this._options));
    }

    public get nonInsurancePayerRefunds(): NonInsurancePayerRefundsClient {
        return (this._nonInsurancePayerRefunds ??= new NonInsurancePayerRefundsClient(this._options));
    }

    public get nonInsurancePayers(): NonInsurancePayersClient {
        return (this._nonInsurancePayers ??= new NonInsurancePayersClient(this._options));
    }

    public get organizationProviders(): OrganizationProvidersClient {
        return (this._organizationProviders ??= new OrganizationProvidersClient(this._options));
    }

    public get organizationServiceFacilities(): OrganizationServiceFacilitiesClient {
        return (this._organizationServiceFacilities ??= new OrganizationServiceFacilitiesClient(this._options));
    }

    public get patientAr(): PatientArClient {
        return (this._patientAr ??= new PatientArClient(this._options));
    }

    public get patientPayments(): PatientPaymentsClient {
        return (this._patientPayments ??= new PatientPaymentsClient(this._options));
    }

    public get patientRefunds(): PatientRefundsClient {
        return (this._patientRefunds ??= new PatientRefundsClient(this._options));
    }

    public get payerPlanGroups(): PayerPlanGroupsClient {
        return (this._payerPlanGroups ??= new PayerPlanGroupsClient(this._options));
    }

    public get payers(): PayersClient {
        return (this._payers ??= new PayersClient(this._options));
    }

    public get serviceLines(): ServiceLinesClient {
        return (this._serviceLines ??= new ServiceLinesClient(this._options));
    }

    public get superbills(): SuperbillsClient {
        return (this._superbills ??= new SuperbillsClient(this._options));
    }

    public get tasks(): TasksClient {
        return (this._tasks ??= new TasksClient(this._options));
    }

    public get writeOffs(): WriteOffsClient {
        return (this._writeOffs ??= new WriteOffsClient(this._options));
    }

    public get preEncounter(): PreEncounterClient {
        return (this._preEncounter ??= new PreEncounterClient(this._options));
    }

    public get diagnoses(): DiagnosesClient {
        return (this._diagnoses ??= new DiagnosesClient(this._options));
    }
}
