/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OrganizationProviderSortOptions = "provider_name:asc" | "provider_name:desc" | "npi:asc" | "npi:desc";

export const OrganizationProviderSortOptions = {
    ProviderNameAsc: "provider_name:asc",
    ProviderNameDesc: "provider_name:desc",
    NpiAsc: "npi:asc",
    NpiDesc: "npi:desc",
} as const;
