/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CandidApi from "../../../../..";

export interface PatientHistoryCategory {
    category: CandidApi.encounters.v4.PatientHistoryCategoryEnum;
    /** Must contain at least one item. */
    questions: CandidApi.encounters.v4.IntakeQuestion[];
}
