/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Patient } from "../types/Patient";

export const Response: core.serialization.Schema<
    serializers.preEncounter.patients.scan.Response.Raw,
    CandidApi.preEncounter.Patient[]
> = core.serialization.list(Patient);

export declare namespace Response {
    type Raw = Patient.Raw[];
}
