// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../index";

export interface TaskUpdateV3 {
    status?: CandidApi.tasks.TaskStatus;
    assigneeUserId?: CandidApi.UserId;
    blocksClaimSubmission?: boolean;
}
