// This file was auto-generated by Fern from our API Definition.

import * as CandidApi from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const ChargeCaptureClaimCreationId: core.serialization.Schema<
    serializers.ChargeCaptureClaimCreationId.Raw,
    CandidApi.ChargeCaptureClaimCreationId
> = core.serialization.string().transform({
    transform: CandidApi.ChargeCaptureClaimCreationId,
    untransform: (value) => value,
});

export declare namespace ChargeCaptureClaimCreationId {
    export type Raw = string;
}
