/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CandidApi from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumberType } from "./PhoneNumberType";

export const PhoneNumberOptional: core.serialization.ObjectSchema<
    serializers.PhoneNumberOptional.Raw,
    CandidApi.PhoneNumberOptional
> = core.serialization.object({
    number: core.serialization.string().optional(),
    type: PhoneNumberType.optional(),
});

export declare namespace PhoneNumberOptional {
    export interface Raw {
        number?: string | null;
        type?: PhoneNumberType.Raw | null;
    }
}
