// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../../../index";

/**
 * @example
 *     {}
 */
export interface CoveragesGetHistoryRequest {
    start?: string;
    end?: string;
    /** If true, only returns coverages that have NOT been auto-updated by the system. */
    nonAutoUpdatedCoveragesOnly?: boolean;
    /** Defaults to ascending. Sorts by version. */
    sortDirection?: CandidApi.preEncounter.SortDirection;
    /** Must be between 0 and 1000. No default. */
    limit?: number;
}
