// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const ContractProviderCount: core.serialization.ObjectSchema<
    serializers.contracts.v3.ContractProviderCount.Raw,
    CandidApi.contracts.v3.ContractProviderCount
> = core.serialization.object({
    providerCount: core.serialization.property("provider_count", core.serialization.number()),
});

export declare namespace ContractProviderCount {
    export interface Raw {
        provider_count: number;
    }
}
