// This file was auto-generated by Fern from our API Definition.

import type * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";
import { ResourcePage } from "../../../../commons/types/ResourcePage";
import { OrganizationProvider } from "../../../../organizationProviders/resources/v2/types/OrganizationProvider";

export const ContractProvidersPage: core.serialization.ObjectSchema<
    serializers.contracts.v3.ContractProvidersPage.Raw,
    CandidApi.contracts.v3.ContractProvidersPage
> = core.serialization
    .object({
        items: core.serialization.list(OrganizationProvider),
    })
    .extend(ResourcePage);

export declare namespace ContractProvidersPage {
    export interface Raw extends ResourcePage.Raw {
        items: OrganizationProvider.Raw[];
    }
}
