// This file was auto-generated by Fern from our API Definition.

import * as CandidApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const RenderingProviderid: core.serialization.Schema<
    serializers.contracts.v3.RenderingProviderid.Raw,
    CandidApi.contracts.v3.RenderingProviderid
> = core.serialization.string().transform({
    transform: CandidApi.contracts.v3.RenderingProviderid,
    untransform: (value) => value,
});

export declare namespace RenderingProviderid {
    export type Raw = string;
}
