// This file was auto-generated by Fern from our API Definition.

export const ClinicalTrialPhase = {
    PhaseOne: "Phase 1",
    PhaseTwo: "Phase 2",
    PhaseThree: "Phase 3",
} as const;
export type ClinicalTrialPhase = (typeof ClinicalTrialPhase)[keyof typeof ClinicalTrialPhase];
